### ISSUE TITLE
Render Urls Present Locally But Not Getting Built and Deployed to Azure Function App

### ISSUE THREAD

**Issue by jonathandbyrd** [Azure/azure-functions-openapi-extension#101]
I have a basic azure function, single http trigger that works correctly doing local debug and  openApi Render URL's are showing up and working fine locally as well. However, on deploying them to Azure Functions  only the single http trigger function appears. The OpenApi Render Urls/Functions are not there.

Env: 0.7.0-preview
.net core 3.1

**Comment by justinyoo** [comment]
@jonathandbyrd Thanks for the issue!

It’s expected behaviour, and you’ll still see the rendering pages like `/api/swagger/ui` or `/api/swagger.json`. But, please use `v0.7.1-preview` or later because `v0.7.0-preview` has a bug on rendering those pages on Azure.

**Comment by jonathandbyrd** [comment]
@justinyoo thanks so much. Yes, its "hidden" I guess be default now? but upgrading to 0.7.1-preview worked.
