### ISSUE TITLE
Enum namingstrategy

### ISSUE THREAD

**Issue by joostvanhassel** [Azure/azure-functions-openapi-extension#103]
When you annotate Enums with `[JsonConverter(typeof(StringEnumConverter))]`, enums will be shown in the schema and accepted as string.

However, there is an inconsistency in casing:

- In the schema and examples, enum (string) values are camelCased
- In actual responses, enum (string) values are returned unchanged (meaning: returned exactly as in code)

I would expect the enum values to exactly match the actual enum value in code in both schema and responses.

**Comment by AnlauTriCloud** [comment]
I experience the same problem

**Comment by RichardPoes** [comment]
This issue has not completely been fixed. When passing an enum as a path parameter, OpenAPI will still use show the enum as camelCased.
