### ISSUE TITLE
Schema of child collection not generated

### ISSUE THREAD

**Issue by jthogsett** [Azure/azure-functions-openapi-extension#105]
When a parent class has a property that's a collection of a child, and the property name is the same as the class name of the child, the child class schema won't get generated.  For example, `public IEnumerable<MultiMedia> MultiMedia { get; set; }`

Edit: To elaborate:
The property will get generated on the parent class
![image](https://user-images.githubusercontent.com/2596159/115934951-06e16480-a447-11eb-879b-bafb031783a2.png)
but in this example, there is no definition of the multiMedia schema.  Here's the error in the swagger ui:
![image](https://user-images.githubusercontent.com/2596159/115935066-41e39800-a447-11eb-9d36-968e51b46dfe.png)

**Comment by dongshinyang** [comment]
Could I take this issue?
