### ISSUE TITLE
"Unknown security definition type" when using OpenApiSecuritySchemeType.Bearer schema

### ISSUE THREAD

**Issue by pavlepiramida** [Azure/azure-functions-openapi-extension#107]
Hi team,

So far setting up OpenApiSecurity as
 ```
        [OpenApiSecurity("jwt"
            , SecuritySchemeType.Http
            , Scheme = OpenApiSecuritySchemeType.Bearer
            , BearerFormat = "JWT"
            , In = OpenApiSecurityLocationType.Header)]
```
has only produced  "Unknown security definition type" on SwaggerUI Authorize modal.

Is anything else needed to make it work?

Currently our workaround is _abuse_ of apikey,

Going through documentation, we didn't notice anything else that might be missing from configuration and according to it, bearer schema should be supported.

**Comment by justinyoo** [comment]
@pavlepiramida Thanks for the issue!

Apparently, you're relying on the OpenAPI 2.0 (Swagger) spec, based on your error message. Unfortunately, it doesn't support the [bearer token format](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityDefinitionsObject). Therefore, if you want to use the bearer token against the OpenAPI 2.0 spec, you should follow the security scheme of `SecuritySchemeType.ApiKey`.

Would you please try it again?

**Comment by pavlepiramida** [comment]
Hi @justinyoo,

Thank you for prompt response!

Yep, that's exactly what we have been doing (with ApiKey) so far to enable things to work!
We were under impression that default OpenAPI spec is 3.x, so decided to flag it...

Guess its back to documentation, obviously we missed something...

**Comment by justinyoo** [comment]
If you implement this interface, `IOpenApiConfigurationOptions`, you’ll be able to set V3 spec as a default behaviour.

samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/Configurations/OpenApiConfigurationOptions.cs

**Comment by nguyenlamlll** [comment]
Hi @justinyoo,
Thank you for your hint. That worked! 
To be more specific, should I do both places like this?
```
public override OpenApiInfo Info { get; set; } = new OpenApiInfo()
{
    Version = OpenApiVersionType.V3.ToString(),
    // ....
}

public override OpenApiVersionType OpenApiVersion { get; set; } = OpenApiVersionType.V3;
```
