### ISSUE TITLE
object support

### ISSUE THREAD

**Issue by AnlauTriCloud** [Azure/azure-functions-openapi-extension#108]
My Azure function contains the following request body:

[OpenApiRequestBody(
            contentType: "application/json",
            bodyType: typeof(Payload)
...]

where the payload class looks something like this:

    public class Payload
    {
        public object value { get; set; }
        ...
    }

In the swagger file it is converted to:

"value": {
    "$ref": "#/definitions/object"
}

I was expecting the following:

"value": {
    "type": "object"
}

The object is apparantly considered a custom type, and this means that a generated client (using NSwag) contains the following:

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Object 
    {  
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Payload 
    {  
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Object Value { get; set; }
 ...

I was expecting this instead:

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
    public partial class Payload 
    {  
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object Value { get; set; }
 ...

It seems like object types are not recognized as a .net type.

**Comment by Lee-WonJun** [comment]
Can I take this issue if it is not resolved?

**Comment by justinyoo** [comment]
@Lee-WonJun Sure!
