### ISSUE TITLE
How to change the Authorization level on the UI and Document?

### ISSUE THREAD

**Issue by russellseymour** [Azure/azure-functions-openapi-extension#110]
I have written an Azure Function that has the OpenAPI Extension in it.

All of the functions that I have written have an authLevel of `function` set. I would like to do the same for the Swagger UI and the OpenAPI Document.

I see from the docs that I should be able to use the `OpenApi__AuthLevel_UI` environment variable setting. But when I set this nothing changes.

In a previous version of the extension, I was able to change the `function.json` file directly to `function` auth which was a bit of a hack. Now I have upgraded to `0.7.1-preview` the "Render" functions are not packaged like that anymore.

I am packaging the function up as a zip file and deploying it into Azure using MSDeploy.

So the question is, how do I compile the app or change a setting so that a function key is generated and I can use function level authorization on the Render functions?

**Comment by russellseymour** [comment]
My apologies, this was caused by a spelling mistake on the environment variable and not using the latest version of the extension.

**Comment by flcdrg** [comment]
@russellseymour Curious where you found docs on setting that environment variable?

**Comment by flcdrg** [comment]
Never mind.. found it! - https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md#configure-authorization-level
