### ISSUE TITLE
API Authentication Not working with API Key

### ISSUE THREAD

**Issue by bnlakshmibn** [Azure/azure-functions-openapi-extension#113]
Please see my local settings
```
{
  "IsEncrypted": false,
  "Values": {
    "OpenApi__ApiKey": "SFJCbG9jay5PY2UuU2VydmljZXMuRm9ybVJlbGVhc2UuQXBp",
    "OpenApi__AuthLevel__Document": "Function",
    "OpenApi__AuthLevel__UI": "Function"
}
```

```
[FunctionName("FormStatus")]
        [OpenApiOperation("FormStatus")]
        public new async Task<IActionResult> GetAllFormStatus(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "formstatus")] HttpRequest req)
        {
            
            return result;
        }
```

When I trigger this, it is getting called without any api key auth

**Comment by justinyoo** [comment]
@bnlakshmibn Thanks for the issue! If you're running on your local machine, you'll see all the UI and doc regardless how you set the auth level. But, if you deploy it to Azure, you'll see the difference.

**Comment by bnlakshmibn** [comment]
> @bnlakshmibn Thanks for the issue! If you're running on your local machine, you'll see all the UI and doc regardless how you set the auth level. But, if you deploy it to Azure, you'll see the difference.

[@justinyoo  So you mean the authentication works only after deployment to Azure? 
What I exactly did is

- I created an azure functions app (v3) (Used dotnet and visual studio 2019)
- I added the azute function class and added the method as shown in the previous message
- Then installed the Microsoft.Azure.WebJobs.Extensions.OpenApi extension
- Added the open api key and settings in local.settings.json
- Started (debug mode) the function and triggered the function (tried both from swagger and postman)
- I didnt provide the api key in either the header or as query
- So what my expectation was, the function will not get called without providing the api key (similar to how we  handle auth in web api's)
- But even without providing the api key in the request, the function is getting executed
So I am confused here.

**Comment by justinyoo** [comment]
@bnlakshmibn Yes, that's expected behaviour. Please refer to [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#api-key-authorization). It says:

> When running functions locally, authorization is disabled regardless of the specified authorization level setting. After publishing to Azure, the `authLevel` setting in your trigger is enforced.

Hope it makes you clear.

**Comment by bnlakshmibn** [comment]
> @bnlakshmibn Yes, that's expected behaviour. Please refer to [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#api-key-authorization). It says:
> 
> > When running functions locally, authorization is disabled regardless of the specified authorization level setting. After publishing to Azure, the `authLevel` setting in your trigger is enforced.
> 
> Hope it makes you clear.

@justinyoo Oh yes. Now its clear. This was where I got confused. Thank you so much for the clarification.
