### ISSUE TITLE
OpenApiRequestBody does not have "byte" type properties populated on Swagger UI

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-openapi-extension#116]
Define a class like the following one code snippet:

```cs
public class Request
{
   public int Id { get; set; }
   public string Name { get; set; }
   public byte State { get; set; }
}
```

Decorate the HTTP-triggered function per the following pattern and you will see that everything is populated but `State` on the Swagger UI.

```cs
[OpenApiRequestBody("application/json", typeof(Request), Required = true)]
```

**Comment by justinyoo** [comment]
@arashcomsense Thanks for the issue! For now, the `byte` data type is not supported.

**Comment by justinyoo** [comment]
Let's chase this up on #96. I'll close this issue
