### ISSUE TITLE
Create proxies.json for Swagger UI

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-functions-openapi-extension#12]
Consider a default proxy for `/swagger` to redirect to the RenderSwaggerDocument endpoint.

[See docs on proxies](https://docs.microsoft.com/azure/azure-functions/functions-proxies)

@justinyoo @bradygaster

**Comment by justinyoo** [comment]
As discussed during the sync-up call, there are two options for us:

1. To provide the default value of `/swagger` through `proxies.json` out-of-the-box. ➡️ It potentially overwrites existing `proxies.json` file.
1. To let developers add or create `proxies.json` by themselves ➡️ It may scratch their development experiences.

I think the Option 1 would be our preference as long as we find a way to inject our proxy value to the existing one.

Can we use both proxy files? I mean, if there are two proxy files, can the AzFunc runtime merge them somehow automagically?

**Comment by bradygaster** [comment]
I prefer option 2 + docs

**Comment by justinyoo** [comment]
Oh, I see. Sounds good!

**Comment by justinyoo** [comment]
Added a doc for this: https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/shortening-swagger-ui-page-url.md @bradygaster @spboyer
