### ISSUE TITLE
Disable "Try it out" button

### ISSUE THREAD

**Issue by mikecole** [Azure/azure-functions-openapi-extension#125]
How can we disable the "Try It Out" button? I see elsewhere to set the `supportedSubmitMethods` property but I cannot figure out how to do that in this context. Thank you.

**Comment by justinyoo** [comment]
You can implement the custom CSS and JavaScript file to disable it. Can you try this way?

**Comment by mikecole** [comment]
Am I missing the documentation or sample that shows how to do this?

**Comment by justinyoo** [comment]
Follow this doc and let us know how it goes: docs/openapi-core.md - UI customisation section
