### ISSUE TITLE
OpenApiExampleAttribute generates a value as a string (instead of maintaining structure)

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-functions-openapi-extension#127]
I noticed that the Swagger generation for OpenApiExampleAttribute just generates a single `value` property with a string value.

When I import the swagger.json into Postman, then it just has an encoded string for the request body example, and I have to remove the extra double quotes and the \ escapes.

Looking over at https://swagger.io/docs/specification/adding-examples/ it seems like ideally the example should be serialised in a way that maintains structure.

So instead of

```json
"example": "{\"id\":123,\"name\":\"Nabi\"}"
```

You'd end up with something like:

```json
"example": {
  "id": 123,
  "name": "Nabi"
}
```

**Comment by flcdrg** [comment]
I suspect this might rely on https://github.com/Azure/azure-functions-openapi-extension/issues/127 or similar being implemented

**Comment by justinyoo** [comment]
@flcdrg That's correct. My implementation relies on it.
