### ISSUE TITLE
Will this work with Isolated Azure Function and dotnet 5.0?

### ISSUE THREAD

**Issue by RobBowman** [Azure/azure-functions-openapi-extension#128]
Hi,

I've followed guidance [here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) to a create a dotnet 5.0 Azure Function App running in an isolated host.

I've added reference to the nuget package Microsoft.Azure.WebJobs.Extensions.OpenApi (0.7.2-preview) and copied the sample "DefaultHttpTrigger" method. The only difference is I need to use the "Function" attribute from the Azure.Functions.Worker namespace rather than the "FunctionName" attributte from the azure.webjobs namespace.

I can run the function app locally ok but I don't get the RenderSwaggerUI endpoint. 

Does anyone know how I can make this work?

**Comment by justinyoo** [comment]
Refer to #22

.NET 5 support is being investigated.
