### ISSUE TITLE
A problem with CORS between azurewebsites.net and azurestaticapps.net

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/azure-functions-openapi-extension#131]
Hi there,
The swagger endpoint loaded fine on my local env, but when I published my Az static web app, I got an error related to CORS and cross-domain-ness.
![image](https://user-images.githubusercontent.com/1428703/120914844-9e54ec80-c66e-11eb-8457-63f9f84e4340.png)

I know this extension is to support Az func descriptions, which is a broader concern that Az static web apps, so it may be that I should be talking to those guys over in Az static web apps, but I thought I'd start here. 

Maybe there are some CORS rules that will allow *.azurewebsites.net and *.azurestaticapps.net to play nice with each other?

**Comment by justinyoo** [comment]
@irwinwilliams Thanks for the issue! Have you tried to add your ASWA URL to your AzFunc app's [CORS settings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#cors)?
