### ISSUE TITLE
Nullable strings are not marked nullable in openapi json

### ISSUE THREAD

**Issue by MartinWickman** [Azure/azure-functions-openapi-extension#133]
When I use a nullable property, they get marked as `"nullable": true` in the json output, which is correct. 

But it seems **this is not the case for strings**. Is this a bug or is it me just being really thick here?

I tried adding `[JsonProperty(Required = Required.AllowNull)]` to the property, but that didn't work either.

This is with version 0.7.2

This is my model

```
    public class Subscription
    {
        public string TheString { get; set; }
        public string? TheNullableString { get; set; }

        public int TheInt { get; set; }
        public int? TheNullableInt { get; set; }

        public DateTimeOffset TheDateTime { get; set; }
        public DateTimeOffset? TheNullableDateTime { get; set; }
```

And this is the output from http://localhost:7071/api/openapi/v3.json

```
      "subscription": {
        "type": "object",
        "properties": {
          "theString": {
            "type": "string"
          },
          "theNullableString": {
            "type": "string"    <--- missing nullable here!
          },
          "theInt": {
            "type": "integer",
            "format": "int32"
          },
          "theNullableInt": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "theDateTime": {
            "type": "string",
            "format": "date-time"
          },
          "theNullableDateTime": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
```

**Comment by MartinWickman** [comment]
Any update on this issue?

**Comment by justinyoo** [comment]
@MartinWickman The `string` property itself allows nullable by default. Instead, if you add `JsonRequired` decorator to your string property, then you will be able to see the `required` attribute.

Please refer to this [doc](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#jsonrequired).

**Comment by MartinWickman** [comment]
Ok, if you say so :) I suppose the problem is in NSwag client (or my code) which I'm using. I reported an [issue there](https://github.com/RicoSuter/NJsonSchema/issues/1380). 

Please keep this open while I'm trying to make sense of this.

**Comment by justinyoo** [comment]
Related: #144

**Comment by justinyoo** [comment]
@MartinWickman I've updated the `OpenApiPropertyAttribute` that you can make use of for your nullable properties. It will be released in the next release. In the meantime, it would be great if you try the code on your end.

**Comment by MartinWickman** [comment]
I just tried and the new attribute works as expected. Thanks for that!

So this:
```
    [OpenApiProperty(Description = "The user's email", Default = "foo@acme.com", Nullable = true)]
    public string? Email { get; set; }
```

Generates this:
```
"email": {
    "type": "string",
    "description": "The user's email",
    "default": "foo@acme.com",
    "nullable": true
},
```

So the attribute solves the problem, which is great but I still seems the nullable `?` type marker is not honored for strings (as in `string? email`), but it is honored for other types (like `int` and enums). 

So you are in effect *required* to use this attribute if you want to have nullable strings.

**Comment by justinyoo** [comment]
The string itself is nullable, isn't it? Why do you put `?` for the string property in the first place?

**Comment by MartinWickman** [comment]
Well, if `<Nullable>enable</Nullable>` is set on the project and I want to allow it to be null, I most certainly need to put `?` to allow nulls, otherwise it won't even compile ([CS8625] Cannot convert null literal to non-nullable reference type), but that's not what you are referring to, right?

**Comment by justinyoo** [comment]
Data types like `int`, `bool`, `DateTime`, etc doesn't allow `null`, while `string` allows it. Therefore, if a property of `int` type needs to be nullable, you should append `?`, for example. However, you don't need the `?` for the `string` because the `string` type allows `null` by default.

I'm not sure whether this behaviour changes when you explicitly enable the nullable feature (like C# 9).

It also needs to consider the `JsonRequired` decorator. Although a property is nullable, if the property is decorated with `JsonRequired`, it shouldn't allow the `null` value.

I think my recent changes overlooked this logic. I'll have a look. Basically, the logic should be...

* If `[JsonRequired]` exists, the property MUST NOT be nullable, regardless the property data type is nullable.
* If `[JsonRequired]` doesn't exist,
  * If the property is NOT decorated with `[OpenApiProperty(Nullable = xxx)]`, The property MUST follow the data type - `int` not nullable, `int?` nullable, `string` nullable, etc
  * If the property is decorated with `[OpenApiProperty(Nullable = xxx)]`, the property MUST follow the decorator declaration, regardless of its data type.

I don't think the currently implemented logic follows the above, which I overlooked. Does it make sense to you?

**Comment by MartinWickman** [comment]
Thanks. Here is the catch, I think: 

If you have [nullable references, c# 8](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types) enabled in your project (as I have) then `string email` is **not allowed to be null**. You get a compilation error if you try to assign it to null. So you absolutely need to put a `?` there. The same goes for all reference types I suppose.

And that's why I'm expecting `string? Email` to generate `nullable: true` in the swagger.json output, but it's not. Probably there is some magic one needs to add to the swagger generating code which can detect this fact, but as it stands now, if nullable is enabled for you proejct, you must remember to add the `[OpenApiProperty(Nullable=true)`.

Otherwise, I agree with your logic: `[JsonRequired]` overrides `[OpenApiProperty(Nullable)]` which overrides the property. Otherwise property settings wins. And if the property is nullable (`?`) it should generate `nullable: true`.

**Comment by justinyoo** [comment]
Thanks for clarifying the `nullable` in C# 8+.

Just make sure that this library targets `netstandard2.0` which supports C# 7.3 by default. As we have to consider as comprehensive as possible, we can't easily change the target framework to `netstandard2.1` that supports C# 8 by default.

Therefore the best available option to make either `string` or `string?` type properties to be `nullable`, you should use the `[OpenApiProperty(Nullable = true)]` decorator.

**Comment by MartinWickman** [comment]
Nice work! Yes, the decorator it’s a proper way to deal with it. Although of course, native support for C#8 would be a nice boon.
