### ISSUE TITLE
Any plans for a stable release?

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-functions-openapi-extension#134]
Any plans for a stable release?

**Comment by justinyoo** [comment]
One of our dependency libraries is currently tagged as preview. Once it becomes GA, we can go GA.

That preview package is used for Logic Apps Standard, which has already become GA. I need to check the status.

/cc: @spboyer @fabiocav

**Comment by tomkerkhove** [comment]
Thanks for the update!

**Comment by justinyoo** [comment]
Just FYI &ndash; this library is a successor of the [Aliencube](https://github.com/aliencube/AzureFunctions.Extensions) one. Although currently it's labelled as "preview", it has richer feature sets than the other one.

**Comment by tomkerkhove** [comment]
We know, that's why we'd love to see this one go stable so we can use this one instead 😁

**Comment by justinyoo** [comment]
Just FYI - we're planning its GA with .NET 6 GA.
