### ISSUE TITLE
OpenAPI query string/path parameter examples

### ISSUE THREAD

**Issue by baltuonis** [Azure/azure-functions-openapi-extension#139]
Now we can create example request/response for post body, which is great!
However we still can't provide examples for query string/path  parameters

Do you, guys, have this in your plans?

https://swagger.io/docs/specification/adding-examples/

**Comment by justinyoo** [comment]
@baltuonis Thanks for the issue! I'll have a look.

**Comment by nuri1126** [comment]
@justinyoo Could you assign this to me? This looks good as my first issue on this project. :)

**Comment by minbumm** [comment]
@justinyoo Please give me permission to do this issue.

**Comment by choipureum** [comment]
Could you assign this to me? 😀

**Comment by justinyoo** [comment]
@choipureum Sure!
