### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#143]
There are several sample apps running in the repo:

* V1 proxy
* V2 IoC
* V2 static
* V3 IoC
* V3 static
* V3 .NET 5

Each sample app has endpoints, and they need to be tested whether they accept parameters correctly and return payloads correctly or not.

Related reading: https://devkimchi.com/2019/08/07/azure-functions-integration-testing-with-mountebank/

**Comment by Deserve82** [comment]
Hi @justinyoo! this is Kangho Lee, can I take this issue as my assignment?

**Comment by justinyoo** [comment]
@Deserve82 That sounds good! Let's discuss how your approach will look like.

**Comment by Lee-WonJun** [comment]
@Deserve82  FYI [Korean Version Blog](https://blog.aliencube.org/ko/2019/08/07/azure-functions-integration-testing-with-mountebank/) of "Related reading"

**Comment by SoniaComp** [comment]
@Deserve82 @justinyoo 
Hi! This is Sun-Young Park, a member of OCA.
Can I take this issue with @Deserve82?

**Comment by choipureum** [comment]
I'd like to participate in this issue.

**Comment by justinyoo** [comment]
@SoniaComp @choipureum Sure. As this is a kind of big chunk, it would be good for all three of you to work together.

**Comment by haileymoon** [comment]
@justinyoo Hi! Can I take part in this issue too? Thanks!

**Comment by minbumm** [comment]
@justinyoo Can I support this issue?

**Comment by changbokLee** [comment]
@justinyoo  Could i take too?

**Comment by justinyoo** [comment]
> @justinyoo Could i take too?

@changbokLee Sorry, there are already too many OCAs interested. Better to find other issues.

**Comment by justinyoo** [comment]
@choipureum @haileymoon I removed both of you from this issue. Let's take other issues you're assigned first then come back here.

**Comment by dongshinyang** [comment]
Can I support this issue?
