### ISSUE TITLE
date format instead of date-time

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-functions-openapi-extension#148]
Is there a way to make types of `System.DateTime` be represented as OpenAPI format 'date' (rather than 'date-time')?

I note that there are [`DateTimeObjectTypeVisitor`](https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DateTimeObjectTypeVisitor.cs) and [`DateTimeTypeVisitor`](https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/DateTimeTypeVisitor.cs) classes in Microsoft.Azure.WebJobs.Extensions.OpenApi.Core but I'm not sure whether I can override or replace those implementations.

eg.

```csharp
public System.DateTime DeliveryDate { get; set; }
```

would be converted to

```yaml
DeliveryDate:
  type: string
  format: date
```

**Comment by justinyoo** [comment]
There's currently no way to represent the `DateTime` type to the `date` format. Let me keep this issue open until finding out a suitable way.
