### ISSUE TITLE
Setting minLength property

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-functions-openapi-extension#151]
Is it possible to set the minLength property (eg. via `[System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 4)]` or similar?

**Comment by justinyoo** [comment]
Related to #76

**Comment by anvudemy** [comment]
Dear team, will be happy to contribute to the projects good first issues. Request to help with where, and how to start...regards
