### ISSUE TITLE
StyleCop produces errors for files downlodaded to .nuget directory

### ISSUE THREAD

**Issue by badmyt** [Azure/azure-functions-openapi-extension#155]
I faced an issue when trying to integrate [StyleCop](https://github.com/StyleCop/StyleCop) into our project, which uses `Microsoft.Azure.WebJobs.Extensions.OpenApi`

StyleCop checks `/.nuget/packages/microsoft.azure.webjobs.extensions.openapi/0.5.1-preview/contentFiles/any/netstandard2.0/OpenApi/` folder and scans codestyle in following files:

`OpenApiHttpTrigger.cs`
`OpenApiHttpTriggerContext.cs`
`IOpenApiHttpTriggerContext.cs`

StyleCop would automatically exclude these files from analysis if they were marked as `<auto-generated>` in the beginning of each file.

Does it worth a fix? Atm it looks not possible to use these two libraries together.

**Comment by justinyoo** [comment]
@badmyt As of v0.8.1-preview, this extension doesn't use the template files. Therefore, it shouldn't be an issue any longer.
