### ISSUE TITLE
Configuration model support

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-functions-openapi-extension#16]
Can we get support for bring your own settings provider. i.e. KeyVault, Azure Config Service

**Comment by justinyoo** [comment]
Thought it would be the metadata configuration model. But it doesn't seem that I initially thought...? 🤔 Can I have an example?

**Comment by spboyer** [comment]
What we are looking for is how IConfiguration is done in ASP.NET Core. See -> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0

**Comment by justinyoo** [comment]
Related to: https://github.com/Azure/azure-functions-host/issues/7126
