### ISSUE TITLE
Invalid function app directory when deployed to azure.

### ISSUE THREAD

**Issue by trevorchunestudy** [Azure/azure-functions-openapi-extension#162]
I have the same issue as #109.  It was marked as closed but no explanation.  Any ideas?  I am deploying via az cli (zipped).  Nothing really all that interesting otherwise to report about it.  It is basically a hello world function app.  Swagger.json displays locally but not deployed.

**Comment by justinyoo** [comment]
@trevorchunestudy Which version of extension are you using? The latest one is 0.7.2-preview. There was an issue on 0.7.1-preview, which was mentioned in #109.

**Comment by trevorchunestudy** [comment]
I got to remember to check that `include pre-releases` checkbox.  I was on 0.7.0.  Unchecked the prelease box (roll-eyes) and upgraded to 0.7.2.  Deployed via pipeline and works correctly.  Thanks @justinyoo  for the very fast response.
