### ISSUE TITLE
OpenApi fails to use a model with a property named Aliases

### ISSUE THREAD

**Issue by IamLeandrooooo** [Azure/azure-functions-openapi-extension#167]
Hi guys, so, I have this model in my solution:

 ```
public class WeatherForecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string Summary { get; set; }

        public List<Aliases> Aliases { get; set; }
    }

    public class Aliases
    {
        public DateTime Date { get; set; }

       
    }
}
```

If I try to add this property to the Function:
`[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(List<WeatherForecast>), Summary = "The response", Description = "This returns a weatherList")]`

And if I try to check the Function Swagger, I get this error:
![image](https://user-images.githubusercontent.com/30774898/124989649-43306400-e037-11eb-8d9f-7b8edd7295ba.png)

If I change the name, the error disappears. 
For example, If I change the property name to Alias I have no problem, but if I make it Aliases it just gives me that error.

Can someone confirm whether or not this word is somehow reserved or is being used in the code and it's giving this error?

I don't know if this is actually related to this, but the azure functions open API extension solution has these 2 js Swagger Files that might be excluding the name:

![image](https://user-images.githubusercontent.com/30774898/124990174-ebdec380-e037-11eb-915f-06483a16fe97.png)

![image](https://user-images.githubusercontent.com/30774898/124990206-f5682b80-e037-11eb-95d2-69c5b0b4c3cc.png)

**Comment by justinyoo** [comment]
That's interesting. Can you change the class name from `Aliases` to `BlackWidows` and property name to `BlackWidows`, and see how it's going?

> NOTE: `BlackWidows` is just an arbitrary name in a plural form. You can change it to `Skywalkers`, if you like.

Try this (class name with `s`):

```csharp
public class BlackWidows
{
    public DateTime Date { get; set; }
}

public class WeatherForecast
{
    ...
    public List<BlackWidows> BlackWidows { get; set; }
}
```

And try this (class name without `s`):

```csharp
public class BlackWidow
{
    public DateTime Date { get; set; }
}

public class WeatherForecast
{
    ...
    public List<BlackWidow> BlackWidows { get; set; }
}
```

**Comment by IamLeandrooooo** [comment]
> ```cs
> BlackWidows 
> ```

So I tried that and indeed failed.

It seems like when the Property has the same name as the class, it fails.

But, as far as I can confirm, it only happens for objects of List<T>, because I have a Property in my main project with the same name of the model but it is like this:

`public Class Class { get; set; }`

and it works.

The moment I change it to List<Class> Class it fails with the Swagger Error.

**Comment by justinyoo** [comment]
Thanks for the confirmation. Let me have a look.

**Comment by IamLeandrooooo** [comment]
> Thanks for the confirmation. Let me have a look.

Thank you very much!
When you have news about it, let me know! 😁

**Comment by kharnt0x** [comment]
We have been seeing this issue but also another one.

When two objects share a list with the same type, that property is excluded from one of the specs. 

i.e. 

```
public class Foo {
 public string firstName {get;set;}
}

public class Bar {
 public List<Foo> Foos {get;set;}
}

public class Baz {
 public List<Foo> Foos {get;set;}
}
```

Will result in a swagger spec where Foos is missing from either Bar or Baz. If I copy the Foo object (say calling it Foo2), and change the type on one of the Lists to use that, everything is generated okay.

**Comment by level120** [comment]
@justinyoo How about this? I think that its aliases have a different reference.

```json
{
  "components": {
    "schemas": {
      "blackWidows": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "weatherForecast": {
        "type": "object",
        "properties": {
          "blackWidows": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/blackWidows"
            }
          }
        }
      }
    }
  }
}
```

The "blackWindows" reference is "#/components/schemas/blackWindows".
The "weatherForecast.blackWindows" reference is "#/components/schemas/weatherForcast/properties/blackWindows".

**Comment by justinyoo** [comment]
@level120 The expected JSON object should be like that, as you mentioned.

```json
{
  "components": {
    "schemas": {
      "blackWidows": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "weatherForecast": {
        "type": "object",
        "properties": {
          "blackWidows": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/blackWidows"
            }
          }
        }
      }
    }
  }
}
```

The current issue is that it's not rendered like that, if there's a property that has a same name of the schema object.

**Comment by level120** [comment]
@justinyoo In my opinion, When instance schema key check skip, it makes the correct script.
I think that subAcceptor having schemas should not check if key same with instance schemas.

![image](https://user-images.githubusercontent.com/10791961/131277898-321d9fb5-d592-4604-abae-c10dc90bd5d4.png)

**Comment by justinyoo** [comment]
@level120 That might be correct. But make sure that the schema only allows the unique name. Can you write relevant codes including test codes that prove your idea?
