### ISSUE TITLE
Programming language support of this extension

### ISSUE THREAD

**Issue by XiaofuHuang** [Azure/azure-functions-openapi-extension#17]
Hello, currently we are also working on generating swagger from Azure Function.
Do you have any plans to support other languages recently? We are looking for a solution to typescript.

**Comment by justinyoo** [comment]
@XiaofuHuang We've got a plan to support other languages but not in near future.

**Comment by aaronpowell** [comment]
In lieu of it not being the goal of this project, I've created my own extension that provides this support - https://github.com/aaronpowell/azure-functions-nodejs-openapi
