### ISSUE TITLE
Incorrect *.deps.json selected leads to no functions found

### ISSUE THREAD

**Issue by fredriklrsn** [Azure/azure-functions-openapi-extension#172]
I have an issue with the open api extension picking the wrong *.deps.json file when determining which dll to search for functions in. This leads to an empty documentation

![image](https://user-images.githubusercontent.com/24248904/125075517-01e39700-e0bf-11eb-97f1-9b2c2f7f9f0e.png)

It seems like the first *.deps.json file is selected.

![image](https://user-images.githubusercontent.com/24248904/125078336-884da800-e0c2-11eb-9a63-9257ccba7ba5.png)

and that it searches through the whole app directory and not just the "bin" folder for these files. The app directory may contain multiple *.deps.json, while the "bin" folder only seem to contain one (function.deps.json) which seems to be the one it should be looking for

![image](https://user-images.githubusercontent.com/24248904/125075917-846c5680-e0bf-11eb-9e51-1af37ea34fe9.png)

Should it search for *.deps.json directly in the "bin" folder (variable: runtimepath) or search specifically for function.deps.json?

**Comment by justinyoo** [comment]
@fredriklrsn Thanks for the issue! Let me have a look.

**Comment by rockgecko-development** [comment]
This may be causing #122  as well

**Comment by kharnt0x** [comment]
This is also causing the same issue when using "func start" from command line to run a function. This causes a /bin/output folder to be generated which contains multiple *.deps.json files, meaning the spec is empty

**Comment by kharnt0x** [comment]
I've confirmed that if I delete the other *.deps.json files in the /bin/output directory generated by "func start", the spec starts working

**Comment by fredriklrsn** [comment]
> @fredriklrsn Thanks for the issue! Let me have a look.

**Comment by fredriklrsn** [comment]
Have you had time to investigate the issue yet, @justinyoo ?

**Comment by justinyoo** [comment]
I basically followed the reproduction step defined at #188. However, I was only able to find one *.deps.json file under the `/bin/Debug/netcoreapp3.1`.

@fredriklrsn @ducman

Here's my local environment:

* OS: Mac OS Catalina: v10.15.7
* .NET Core 3.1 SDK: v3.1.412
* AzFunc Core Tools: v3.0.3568
* Azure Functions OpenAPI Extension: v0.8.1-preview

**Comment by choipureum** [comment]
I also have the same issue that sample code swagger.ui does not work. Swagger.ui works only when the sample code is debug. But it doesn't work when `func start` in shell. I also think `/bin/output/` folder has a problem getting multiple deps.json, including function.deps.json. I am currently testing the case of swagger.json operating during operation. I am testing based on the difference between debug and system startup.

1. `func start ` in shell
![image](https://user-images.githubusercontent.com/55127127/130411696-ccc07756-232c-4cdd-8c23-d2fa646e4778.png)
 
2. debug mode sample
![image](https://user-images.githubusercontent.com/55127127/130412215-d882bfcf-cc0e-4946-95ef-7f5575a62027.png)

**Comment by justinyoo** [comment]
@fredriklrsn It's resolved, and @vincentbitter 's contribution has been merged to the main repo (not yet published).

Would you please try the new change on your end and let us know?

**Comment by fredriklrsn** [comment]
Great. I will test as soon as it is published.

**Comment by jwadaptivity** [comment]
hey @justinyoo , any updates on when this will be published?

**Comment by fredriklrsn** [comment]
Probably a bit late since it is out of preview now, but I have tried testing this and been getting a different error so I have not been able to verify that it works.
