### ISSUE TITLE
OpenApiRequestBody.Description missing in rendered requestBody

### ISSUE THREAD

**Issue by sharpt00th** [Azure/azure-functions-openapi-extension#174]
When setting property **Description** in an OpenApiRequestBody attribute, this text is omitted from the Swagger output (specifically, as a property of requestBody).
This issue can be observed using the PetStoreHttpTrigger sample, in method UpdatePet which has the attribute set as follows:

`[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(Pet), Required = true, Description = "Pet object that needs to be updated to the store")]`

The rendered Swagger for this method's request:

```
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "$ref": "#/components/schemas/pet"
      }
    }
  },
  "required": true
}
```

I _think_ I've traced the issue to class Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper method GetOpenApiRequestBody - I tested the following change with success:
```
return new OpenApiRequestBody()
                {
                    Content = contents,
                    Required = attributes.First().Required,
                    Description = attributes.First().Description
                };
```

**Comment by emrekara37** [comment]
Hi, @sharpt00th  
I started a PR with your solution
