### ISSUE TITLE
BlobNotFound installing from nuget.org

### ISSUE THREAD

**Issue by Sebosek** [Azure/azure-functions-openapi-extension#175]
Hi,

getting BlobNotFound during installation from nuget.org. Is something happening or a temporary outage?
![image](https://user-images.githubusercontent.com/372542/125194206-94677000-e250-11eb-8b28-57b73858c7ac.png)

**Comment by justinyoo** [comment]
@Sebosek Yes, we're aware of it and in the middle of fixing it. In the meantime, please stay at 0.7.2-preview.
