### ISSUE TITLE
Add a sample for describing a multipart/form-data endpoint for file uploads

### ISSUE THREAD

**Issue by trevonmckay** [Azure/azure-functions-openapi-extension#18]
I'm not sure what the bodyType would be for an endpoint that accepts multipart/form-data using the OpenApiRequestBodyAttribute.

**Comment by justinyoo** [comment]
It's not currently supported yet, but it will be implemented.

**Comment by justinyoo** [comment]
Related to https://github.com/aliencube/AzureFunctions.Extensions/issues/111 and https://github.com/aliencube/AzureFunctions.Extensions/issues/71

**Comment by agravity-philipp** [comment]
Any update on this? I would really need it :)

**Comment by klaudiaknafel** [comment]
Are there any updates on when it will be implemented?

**Comment by ParimalPa** [comment]
We are in need of this - when would this be available?

**Comment by Nikhil-RT** [comment]
Hi @justinyoo, may I know if "Content-Type" : "multipart/form-data" supported for azure rest api's ....?

**Comment by Vivekv11** [comment]
Hi @justinyoo, do you have any updates regarding the issue with uploading multiple files? Currently, when providing byte[] it only populates one file upload section in swagger. Is there a possibility to use IFormFile or IFormFileCollection instead of byte[]?
