### ISSUE TITLE
Revising .NET 5 / Isolated Worker Support

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#182]
As the current codebase needs to be restructured, the .NET 5 and isolated worker support also needs to be revised.

**Comment by justinyoo** [comment]
Related to #22

**Comment by joostvanhassel** [comment]
What will be revised and will this block a release of the current implementation as `0.8.0`?

**Comment by justinyoo** [comment]
The current approach of .NET 5 (and isolated worker) support is no longer valid. I'll remove all the related logics. The rest will be published to `v0.8.1-preview` soon.

**Comment by justinyoo** [comment]
Related to: https://github.com/Azure/azure-functions-dotnet-worker/issues/562

**Comment by justinyoo** [comment]
Interim workaround: #187

**Comment by OlegGavrilov** [comment]
> Dependency: [Azure/azure-functions-dotnet-worker#562](https://github.com/Azure/azure-functions-dotnet-worker/issues/562)

Any chance for ETA? We are really looking forward for swagger in our isolated functions apps. Thanks!

**Comment by justinyoo** [comment]
The `v0.8.1-preview` packages are under review before publishing to nuget.org. Once the review is done, it will be released. @fabiocav Would you please give us ETA for publish?

**Comment by justinyoo** [comment]
Released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.OpenApi
