### ISSUE TITLE
How to override the openAPi title,version and description

### ISSUE THREAD

**Issue by abhishek14anandDev** [Azure/azure-functions-openapi-extension#184]
How to override the openAPi title,version and description.

It always comes with Azure Functions Open API Extension

**Comment by justinyoo** [comment]
Please inherit [`DefaultOpenApiConfigurationOptions`](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#inheriting-defaultopenapiconfigurationoptions)
