### ISSUE TITLE
Missing definition

### ISSUE THREAD

**Issue by AdrianoAE** [Azure/azure-functions-openapi-extension#186]
I'm using the version 0.7.2 and my response type is the following case:

```
public class Response
{
    public string Test { get; set; }
    public Test[] MyProperty { get; set; }
}

public class Test
{
    public int MyProperty { get; set; }
}
```

The schema for the Test class won't be generated becase of the property with the same name, if we change it to any other name it works as intended

Another problem is with generics

```
public class BaseResponse<T>
{
    public T Data { get; set; }
}

//using
[OpenApiResponseWithBody(..., bodyType: typeof(BaseResponse<List<Response>>))]
```

This generates a schema called "baseResponse_list`1" which is problematic with Azure APIM

**Comment by level120** [comment]
I think it is related to https://github.com/Azure/azure-functions-openapi-extension/issues/167
There is working on https://github.com/Azure/azure-functions-openapi-extension/pull/218

**Comment by justinyoo** [comment]
It's slightly different from #167 and #218

This issue is about generic inside generic.
