### ISSUE TITLE
public fields not being added to spec

### ISSUE THREAD

**Issue by kharnt0x** [Azure/azure-functions-openapi-extension#191]
It looks like public List fields are not being added to openapi specs, while auto-properties work fine. 

For example this doesn't get added to spec

`        public List<ParentReceipt> ParentReceipts = new List<ParentReceipt>();
`

While this does 
`                public List<ParentReceipt> ParentReceipts { get; set; } = new List<ParentReceipt>();
`

**Comment by justinyoo** [comment]
@kharnt0x Thanks for the issue. That's correct. Fields are not considered to expose.
