### ISSUE TITLE
Override DateTime to display as "date" format in specification

### ISSUE THREAD

**Issue by kevinmillstx** [Azure/azure-functions-openapi-extension#193]
Is there a way to have specific DateTime properties be output with "format": "date" instead of "format": "date-time". Hopefully this is not an issue with .Net 6 DateOnly, but would be nice to have a simple solution in the interim. I'm using a custom DateOnly converter to process the data, but since the specification is automatically generated, all dates are presented as date-time.

**Comment by kevinmillstx** [comment]
I previously tried the `[DataType(DataType.Date)]` annotation, but it wasn't working on v0.7.2. However, it's now working using 0.8.1 (for out of process version, Thank you!), but only for non-nullable DateTime. Nullable DateTime still returns `date-time` format.

**Comment by h0s** [comment]
@kevinmillstx  i will be happy to get this , but can you please give more information and repro steps , 
versions , sample code and the goal ?

**Comment by kevinmillstx** [comment]
The goal would be that a nullable DateTime property would have a type and format of string($date) in generated OpenAPI specification.

Example class with non-nullable DateTime and nullable DateTime, both annotated with [System.ComponentModel.DataAnnotations.DataType(DataType.Date)]:

`public class Test
{
	[DataType(DataType.Date)]
	public DateTime NonNullableDate { get; set; }
	[DataType(DataType.Date)]
	public DateTime? NullableDate { get; set; }
}`

Below are two examples using version 0.8.1 version of OpenAPI packages. Both schema examples show that non-nullable DateTime has correct format, while nullable DateTime does not.

Using .Net 5.0 Out of Process Functions App:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="0.8.1-preview" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

Function annotations:

`[Function("Function1")]
[OpenApiOperation(operationId: nameof(Run), tags: new[] { "name" })]
[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
[OpenApiParameter(name: "name", In = ParameterLocation.Query, Required = true, Type = typeof(string), Description = "The **Name** parameter")]
[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(Test), Description = "Test", Required = true)]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Description = "The OK response")]`

Generated schema showing different formats:

`"schemas": {
  "test": {
	"type": "object",
	"properties": {
	  "nonNullableDate": {
		"type": "string",
		"format": "date"
	  },
	  "nullableDate": {
		"type": "string",
		"format": "date-time",
		"nullable": true
	  }
	}
  }
},`

Using .Net 3.1 In Process Functions App:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.8.1-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

Function annotations:

`[FunctionName("Function1")]
[OpenApiOperation(operationId: "Run", tags: new[] { "name" })]
[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
[OpenApiParameter(name: "name", In = ParameterLocation.Query, Required = true, Type = typeof(string), Description = "The **Name** parameter")]
[OpenApiRequestBody(contentType: "application/json", bodyType: typeof(Test), Description = "Test", Required = true)]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Description = "The OK response")]

Generated schema showing different formats:

`"schemas": {
  "test": {
	"type": "object",
	"properties": {
	  "nonNullableDate": {
		"type": "string",
		"format": "date"
	  },
	  "nullableDate": {
		"type": "string",
		"format": "date-time",
		"nullable": true
	  }
	}
  }
},`

**Comment by choipureum** [comment]
Oh, I'm sorry. I didn't see the comment, so I sent a PR about this first. 😓
