### ISSUE TITLE
swagger.json - Sequence contains no elements

### ISSUE THREAD

**Issue by OskarNet** [Azure/azure-functions-openapi-extension#194]
Hi

I've a functions project that throws this error in the console when requesting the swagger.json:
 Sequence contains no elements

There is only HTTPTrigger function with the OpenApiOperation, OpenApiParameter and OpenApiResponseWithBody attributes.
```
[OpenApiOperation("Get resource", "Get resource")]        
[OpenApiParameter("cId", In = Microsoft.OpenApi.Models.ParameterLocation.Query, Required = true, Type = typeof(string))]
[OpenApiParameter("aId", In = Microsoft.OpenApi.Models.ParameterLocation.Query, Required = true, Type = typeof(string))]
[OpenApiParameter("rId", In = Microsoft.OpenApi.Models.ParameterLocation.Query, Required = true, Type = typeof(string))]
[OpenApiResponseWithBody(System.Net.HttpStatusCode.OK, StringConstants.JsonContentType, typeof(ResourceResultModel))]

```

**Error in the UI:**
![image](https://user-images.githubusercontent.com/57990676/129224052-1fa1792a-9910-4b9d-a87f-3a09502ec6fa.png)

Regards,
Oskar

**Comment by emrekara37** [comment]
Hi @OskarNet 
Can you share your ResultModel ? 
Maybe i can help you

**Comment by OskarNet** [comment]
Sure. Here it is:

` public class ResourceResultModel
    {
        public string ResourceId { get; set; }
        public byte[] Bytes { get; set; }
    }`

**Comment by emrekara37** [comment]
> Sure. Here it is:
> 
> ` public class ResourceResultModel { public string ResourceId { get; set; } public byte[] Bytes { get; set; } }`

Related to : #96
