### ISSUE TITLE
Every function stop work after I imported OpenAPI configuration to existed API in API Management

### ISSUE THREAD

**Issue by DennYats** [Azure/azure-functions-openapi-extension#197]
So I had API(Azure Functions) in API Management imported directly from Azure Functions
![image](https://user-images.githubusercontent.com/45600211/129442480-930cb408-1afb-4cb7-9c50-f431061806c4.png)

After I imported new version of AF through OpenAPI configuration url despite I chosen Update option when we update replace whole AP, it still returns 500 error
![image](https://user-images.githubusercontent.com/45600211/129442591-b194649f-961c-4f58-92f9-904e25f0d13b.png)

Here is Trace: 
**Inbound**
> api-inspector (0.240 ms)
>     {
>     "request": {
>         "method": "GET",
>         "url": "https://yats-api-management-test.azure-api.net/todo-function/Function1?name=de",
>         "headers": [
>             {
>                 "name": "sec-ch-ua",
>                 "value": "\"Chromium\";v=\"92\",\" Not A;Brand\";v=\"99\",\"Microsoft Edge\";v=\"92\""
>             },
>             {
>                 "name": "DNT",
>                 "value": "1"
>             },
>             {
>                 "name": "sec-ch-ua-mobile",
>                 "value": "?0"
>             },
>             {
>                 "name": "Ocp-Apim-Subscription-Key",
>                 "value": "d6c5668e44534a8d8a329bdba23cd902"
>             },
>             {
>                 "name": "Sec-Fetch-Site",
>                 "value": "cross-site"
>             },
>             {
>                 "name": "Sec-Fetch-Mode",
>                 "value": "cors"
>             },
>             {
>                 "name": "Sec-Fetch-Dest",
>                 "value": "empty"
>             },
>             {
>                 "name": "X-Forwarded-For",
>                 "value": "109.229.30.112"
>             },
>             {
>                 "name": "Cache-Control",
>                 "value": "no-cache, no-store"
>             },
>             {
>                 "name": "Content-Type",
>                 "value": "text/plain;charset=UTF-8"
>             },
>             {
>                 "name": "Accept",
>                 "value": "*/*"
>             },
>             {
>                 "name": "Accept-Encoding",
>                 "value": "gzip,deflate,br"
>             },
>             {
>                 "name": "Accept-Language",
>                 "value": "en-US,en;q=0.9"
>             },
>             {
>                 "name": "Host",
>                 "value": "yats-api-management-test.azure-api.net"
>             },
>             {
>                 "name": "Referer",
>                 "value": "https://apimanagement.hosting.portal.azure.net/"
>             }
>         ]
>     }
> }
> api-inspector (0.002 ms)
>     {
>     "configuration": {
>         "api": {
>             "from": "/todo-function",
>             "to": {
>                 "scheme": "https",
>                 "host": "todo-function.azurewebsites.net",
>                 "port": 443,
>                 "path": "/api",
>                 "queryString": "",
>                 "query": {},
>                 "isDefaultPort": true
>             },
>             "version": null,
>             "revision": "1"
>         },
>         "operation": {
>             "method": "GET",
>             "uriTemplate": "/Function1?name={name}"
>         },
>         "user": "-",
>         "product": "-"
>     }
> }
> cors (0.018 ms)
>     "Origin header was missing or empty and the request was classified as not cross-domain. CORS policy was not applied."
> set-backend-service (0.007 ms)
>     {
>     "message": "Backend service URL was changed.",
>     "oldBackendServiceUrl": "https://todo-function.azurewebsites.net/api",
>     "newBackendServiceUrl": "https://localhost:7071/api",
>     "request": {
>         "url": "https://localhost:7071/api/Function1?name=de"
>     }
> }

**Backend**

> forward-request (0.089 ms)
>     {
>     "message": "Request is being forwarded to the backend service. Timeout set to 300 seconds",
>     "request": {
>         "method": "GET",
>         "url": "https://localhost:7071/api/Function1?name=de",
>         "headers": [
>             {
>                 "name": "Host",
>                 "value": "localhost:7071"
>             },
>             {
>                 "name": "sec-ch-ua",
>                 "value": "\"Chromium\";v=\"92\",\" Not A;Brand\";v=\"99\",\"Microsoft Edge\";v=\"92\""
>             },
>             {
>                 "name": "Request-Id",
>                 "value": "|b0ff3d5c-452d005ad95af3d9.b0ff3d5d_"
>             },
>             {
>                 "name": "DNT",
>                 "value": "1"
>             },
>             {
>                 "name": "sec-ch-ua-mobile",
>                 "value": "?0"
>             },
>             {
>                 "name": "Ocp-Apim-Subscription-Key",
>                 "value": "d6c5668e44534a8d8a329bdba23cd902"
>             },
>             {
>                 "name": "Sec-Fetch-Site",
>                 "value": "cross-site"
>             },
>             {
>                 "name": "Sec-Fetch-Mode",
>                 "value": "cors"
>             },
>             {
>                 "name": "Sec-Fetch-Dest",
>                 "value": "empty"
>             },
>             {
>                 "name": "X-Forwarded-For",
>                 "value": "109.229.30.112,13.91.254.72"
>             },
>             {
>                 "name": "Cache-Control",
>                 "value": "no-cache, no-store"
>             },
>             {
>                 "name": "Content-Type",
>                 "value": "text/plain;charset=UTF-8"
>             },
>             {
>                 "name": "Accept",
>                 "value": "*/*"
>             },
>             {
>                 "name": "Accept-Encoding",
>                 "value": "gzip,deflate,br"
>             },
>             {
>                 "name": "Accept-Language",
>                 "value": "en-US,en;q=0.9"
>             },
>             {
>                 "name": "Referer",
>                 "value": "https://apimanagement.hosting.portal.azure.net/"
>             },
>             {
>                 "name": "Request-Context",
>                 "value": "appId=cid-v1:092ad043-1d34-4a29-8652-fb3bf1646dd2"
>             }
>         ]
>     }
> }
> forward-request (2,042.039 ms)
>     {
>     "messages": [
>         "Unable to connect to the remote server",
>         "Error occured while calling backend service.",
>         "No connection could be made because the target machine actively refused it 127.0.0.1:7071"
>     ]
> }

**Outbound**

> transfer-response (0.168 ms)
>     {
>     "message": "Response has been sent to the caller in full"
> }`
 
I see strange row in Cors section 
> `cors (0.018 ms)
>     "Origin header was missing or empty and the request was classified as not cross-domain. CORS policy was not applied."
> set-backend-service (0.007 ms)
>     {
>     "message": "Backend service URL was changed.",
>     "oldBackendServiceUrl": "https://todo-function.azurewebsites.net/api",
>     **"newBackendServiceUrl": "https://localhost:7071/api",**
>     "request": {
>         "url": "https://localhost:7071/api/Function1?name=de"
>     }
> }

**localhost:7071** could it happen because of wrong deployment?

**Comment by DennYats** [comment]
Update: I Applied set-backend policy and it works, but is there any way to do this automaticall?

**Comment by justinyoo** [comment]
instead of doing that, can you use OpenAPI URL for APIM import?
