### ISSUE TITLE
Test failed on Visual Studio

### ISSUE THREAD

**Issue by level120** [Azure/azure-functions-openapi-extension#201]
I have some problems with a test project, commit [689113e](https://github.com/Azure/azure-functions-openapi-extension/commit/689113e34e19abd3a9d224252c4c51cde89133f0)

I tried three environments, CLI, ReSharper, and test explorer in visual studio(build in).
CLI and ReSharper test are all passes but test explorer is not.

Unfortunately failed cases are random.

The below picture is Test Explorer in Visual Studio.
![image](https://user-images.githubusercontent.com/10791961/130235435-91300a07-8a63-4fa8-ab52-48b47a4a4c35.png)

On Resharper.
![image](https://user-images.githubusercontent.com/10791961/130235645-73a3e0b9-9a50-4483-ae71-bae755887b59.png)

On CLI with `dotnet test` command.
![image](https://user-images.githubusercontent.com/10791961/130235816-07834444-cc85-474d-9293-a145bf155da7.png)

**Comment by justinyoo** [comment]
@level120 Thanks for the issue! As long as the test passes with dotnet CLI, it's OK for now. But your question is still valid.

I'm not sure it's the issue on our side or Visual Studio's test explorer side, though.
