### ISSUE TITLE
 Support for ValueTuple type in response body type

### ISSUE THREAD

**Issue by Lee-WonJun** [Azure/azure-functions-openapi-extension#205]
### Describe 
Tuple and ValueTuple seem to have the same response. 
However, when ValueTuple type is used for Description, "Example" (or Schema) is not described normally.

For example, I wrote the code like this, (check body Type). Then I check the response && swagger.

<details markdown="1">
<summary>code </summary>

```csharp
[Function(nameof(PetStoreHttpTrigger.SystemTupleHandler))]
[OpenApiOperation(operationId: "SystemTupleHandler", tags: new[] { "tuple" })]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(Tuple<int,double,string>))]
public async Task<Tuple<int,double,string>> SystemTupleHandler(
   [HttpTrigger(AuthorizationLevel.Function, "GET", Route = "system-tuple")] HttpRequestData req,
   FunctionContext executionContext)
{
    var tuple = Tuple.Create(1,1.5,"3");
    return await Task.FromResult(tuple).ConfigureAwait(false);
}

[Function(nameof(PetStoreHttpTrigger.SystemValueTupleHandler))]
[OpenApiOperation(operationId: "SystemValueTupleHandler", tags: new[] { "tuple" })]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(ValueTuple<int, double, string>))]
public async Task<ValueTuple<int, double, string>> SystemValueTupleHandler(
   [HttpTrigger(AuthorizationLevel.Function, "GET", Route = "system-valuetuple")] HttpRequestData req,
   FunctionContext executionContext)
{
    var tuple = ValueTuple.Create(1, 1.5, "3");
    return await Task.FromResult(tuple).ConfigureAwait(false);
}

[Function(nameof(PetStoreHttpTrigger.SystemValueTupleSyntaxHandler))]
[OpenApiOperation(operationId: "SystemValueTupleSyntaxHandler", tags: new[] { "tuple" })]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof((int,double,string)))]
public async Task<(int,double,string)> SystemValueTupleSyntaxHandler(
  [HttpTrigger(AuthorizationLevel.Function, "GET", Route = "system-valuetuplesyntax")] HttpRequestData req,
  FunctionContext executionContext)
{
    var tuple = (1, 1.5, "3");
    return await Task.FromResult(tuple).ConfigureAwait(false);
}

```

</details>

<details markdown="1">
<summary>Response / swagger </summary>

![image](https://user-images.githubusercontent.com/10369528/130352262-61627fb8-c173-4980-8466-b82fd383b79d.png)

</details>

### Env Information
- Windows 10 Education (21H1)
- Azure Function Local Test

**Comment by justinyoo** [comment]
@Lee-WonJun Thanks for the issue! According to your code, you're using .NET 5.

Would you please return the `HttpResponseData` object instead of the Tuple object and see how it's going?

**Comment by Lee-WonJun** [comment]
> @Lee-WonJun Thanks for the issue! According to your code, you're using .NET 5.
> 
> Would you please return the `HttpResponseData` object instead of the Tuple object and see how it's going?

I'll check soon,

But, IMHO, the important thing is that swagger shows empty.
It's about "attributes", isn't it about the actual "response"?

**Comment by justinyoo** [comment]
@Lee-WonJun You're exactly right. We need to look for the both Tuple and ValueTuple types.

**Comment by Lee-WonJun** [comment]
I found the reason.
in the [document]( (https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-4?view=net-5.0))
"Members like Item1 and Item2 are fields, not properties." content can be found

So it is not automatically serialized.
I'll  be able to make new visitor for ValueTuple.

**Comment by Lee-WonJun** [comment]
in the same [document](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-4?view=net-5.0)

```
The ValueTuple type is not serializable in .NET Core 1.x or in the .NET Framework 4.7 and earlier versions. In addition, .NET Standard, including .NET Standard 2.0, does not mandate serialization of ValueTuple instances; whether or not a ValueTuple instance is serializable depends on the individual .NET Standard implementation. To determine whether a ValueTuple type is serializable on a particular .NET implementation, get a Type object that represents the ValueTuple type and retrieve the value of its IsSerializable property. For a list of serializable types in .NET Core and the .NET Framework, see Binary Serialization.
```

Serialization is no mandatory in .Net.

According to the documentation, serialization for ValueTuple is implementation specific.

Therefore, it seems that this problem does not need to be implemented at this point.

**Comment by justinyoo** [comment]
@Lee-WonJun Thanks for the detailed research and conclusion. Really appreciate your efforts! I'm going to close it for now.
