### ISSUE TITLE
Building the program on Windows

### ISSUE THREAD

**Issue by minbumm** [Azure/azure-functions-openapi-extension#206]
![error](https://user-images.githubusercontent.com/68464294/130355083-8040c6b6-4683-4fb2-bbf8-91013f5c1ddf.png)

Building the program on Windows exceeds the MSB349 OS maximum path limit. An error occurs.

**Comment by Lee-WonJun** [comment]
OS limitation [link](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)

Either allow the long path in your OS or use a short path for your project (in my case, rename the root directory).

**Comment by justinyoo** [comment]
@minbumm Thanks for the issue! As @Lee-WonJun mentioned above, it's the Windows' limitation. The solution could be either:

1. Enable long path, or
2. Keep the cloned repository's name as short as you can.

**Comment by Lee-WonJun** [comment]
IMHO, we need a guide document for building and setting up the environment, and it would be nice if we could provide this as a note.
