### ISSUE TITLE
Failed to fetch http://somefunctionname.azurewebsites.net/swagger.json - The page was loaded over https:// but a http:// URL was specified

### ISSUE THREAD

**Issue by dr-dolittle** [Azure/azure-functions-openapi-extension#215]
Microsoft.Azure.WebJobs.Extensions.OpenApi v0.8.1-preview

The extension works locally when I make a request to https://somefunctionname.azurewebsites.net/swagger/ui. When I deploy the Azure Function to Azure https://somefunctionname.azurewebsites.net/swagger.json also works. But when I try https://somefunctionname.azurewebsites.net/swagger/ui I get

```
Fetch errorFailed to fetch http://somefunctionname.azurewebsites.net/swagger.json
Fetch errorPossible mixed-content issue? The page was loaded over https:// but a http:// URL was specified. Check that you are not attempting to load mixed content.
```

![image](https://user-images.githubusercontent.com/26380370/130907734-968e5500-263f-48ab-952b-1e7c6f004787.png)

When I then update the Explore URI to https it works

![image](https://user-images.githubusercontent.com/26380370/130907924-5f7cdf57-8ecf-4e1e-ab98-0538c914a143.png)

Is this a bug or do I miss a setting to work with HTTPS on the first request?

Thanks

**Comment by mlowijs** [comment]
@justinyoo What do you mean it is something you can't handle? Is it not possible to offer this as a configuration option or something like that?

**Comment by justinyoo** [comment]
It's not the issue on the extension side.

That only occurs on the Linux-based instance, which I suspect that the instance internally uses a reverse proxy or something similar to handle all the traffic in HTTP, not HTTPS.

Alternatively, as the UI script relies on https://github.com/swagger-api/swagger-ui, it's better to ask them for workaround. I have no visibility to the Swagger UI scripts.

**Comment by justinyoo** [comment]
But, let me take a look at this issue. I might have an idea how to fix this.

**Comment by shlee7131** [comment]
Can I join this problem?

**Comment by justinyoo** [comment]
@shlee7131 Alright. I'll assign this issue to you. As I've done some base work before you jumped on this issue, you can continue your contribution on the [`feature/force-https`](https://github.com/Azure/azure-functions-openapi-extension/tree/feature/force-https) branch.

In the branch, you'll see the new property, `ForceHttps` on the `IOpenApiConfigurationOptions` interface.

https://github.com/Azure/azure-functions-openapi-extension/blob/673960e332be2e179f8fe3d6c3fc8aaa227ddb7b/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Abstractions/IOpenApiConfigurationOptions.cs#L36

With this property, find the `AddServer(...)` method on both [`src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs`](https://github.com/Azure/azure-functions-openapi-extension/blob/feature/force-https/src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs)

https://github.com/Azure/azure-functions-openapi-extension/blob/673960e332be2e179f8fe3d6c3fc8aaa227ddb7b/src/Microsoft.Azure.Functions.Worker.Extensions.OpenApi/Document.cs#L76

https://github.com/Azure/azure-functions-openapi-extension/blob/673960e332be2e179f8fe3d6c3fc8aaa227ddb7b/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs#L72

and [`src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs`](https://github.com/Azure/azure-functions-openapi-extension/blob/feature/force-https/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/Document.cs).

Then, apply the `ForceHttps` property value to the line I specified.

Please let me know if you have any question around this.

**Comment by mikemassa84** [comment]
@dr-dolittle I reported this same issue, and found this work around:

https://github.com/Azure/Azure-Functions/issues/1933#issuecomment-889178952

Hope it helps.

@justinyoo The azure functions team punted this issue back to you.
