### ISSUE TITLE
Required Attribute

### ISSUE THREAD

**Issue by MrWolfPST** [Azure/azure-functions-openapi-extension#226]
Add support for System.ComponentModel.DataAnnotations.RequiredAttribute besides Newtonsoft.Json.JsonRequiredAttribute

**Comment by justinyoo** [comment]
@MrWolfPST Thanks for the issue! Would you please elaborate?

**Comment by MrWolfPST** [comment]
I maked some additional tests and I must partial review the issue.
The only way I found for include a mandatory property in the required section of component is decorate property with [JsonProperty(Required = Required.Always)].
Instead if I use JsonRequired or Required attributes, property is not included in the required section.
Anyway the RequiredAttribute is not in the supportet attributes list

**Comment by justinyoo** [comment]
Here are the decorators we currently support:

* From [Newtonsoft.Json](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#supported-jsonnet-decorators)
* From [System.ComponentModel.DataAnnotations](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#supported-systemcomponentmodeldataannotations-decorators)

It partially answers your question, though.

**Comment by MrWolfPST** [comment]
Yes I had read. My original request was for add support of RequiredAttribute of System.ComponentModel.DataAnnotations namespace. But seam that also JsonRequiredAttribute have some problem

**Comment by justinyoo** [comment]
Let me check.

**Comment by MrWolfPST** [comment]
JsonRequered not working in combination with JsonProperty with property name specified, as described in issue #227

**Comment by tommck** [comment]
I'm using the latest versions of this and .NET 6 and Azure Functions v4 and The Required Attribute does not seem to work at all.
