### ISSUE TITLE
HashSet is rendered as an object in the swagger example and spec

### ISSUE THREAD

**Issue by MartinWickman** [Azure/azure-functions-openapi-extension#229]
Creating a model class which contains a `HashSet` will render it like a json object in the example part of the swagger documentation url (http://localhost:7071/api/swagger/ui). For example, this model:

```
    public class Station
    {
        public HashSet<GasType> GasTypes { get; set; } = new HashSet<GasType>();
    }
```

Renders like this in the Example box:

```
    "gasTypes": {
       "count": 0,
       "comparer": {}
    },
```

![image](https://user-images.githubusercontent.com/900766/132198985-5952f700-3bf4-49bf-bedd-70f36a6fcd61.png)

The generated swagger spec looks like this:

![image](https://user-images.githubusercontent.com/900766/132199830-c1d9c09b-a3fa-41a9-afe6-e14561b69a0b.png)

But the actual json string that is returned when calling the azure http function is generated as a plain json array with string values. So there is some kind of discrepancy going on here. This what is returned:

`  "gasTypes": [ "foo", "bar" ]`

**Comment by justinyoo** [comment]
@MartinWickman Thanks for the issue! I'm working on it.
