### ISSUE TITLE
Support AAD authentication for swagger UI endpoint

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-functions-openapi-extension#232]
Please provide support for AAD authentication on swagger UI endpoint. 

One current workaround that is not a very pleasant experience is to enable EasyAuth on the whole function app with a redirection to the login page if user is not authenticated. However, it would redirect twice and make the user sign in twice, one for the swagger json and the other one for the UI.

**Comment by justinyoo** [comment]
@chinarosesz Thanks for the issue!

Currently, both Swagger UI and OpenAPI doc endpoints only support the AzFunc's built-in API key auth flow. But let me take a look how we can sort out this challenge.

Just on top of my head, I'm considering our `IOpenApiConfigurationOptions` to apply.

**Comment by justinyoo** [comment]
I'm looking `OpenApiHttpTriggerContext` for this. The basic idea is that I would add a method like `AuthorizeAsync(...)`, then the method is called within each endpoint like:

```csharp
result = await (await this._context
                          .SetApplicationAssemblyAsync(fi.Directory.FullName, appendBin: false)
                          .AuthorizeAsync(request))
                          .Document
...
```

The auth logic should be customisable because every organisation deals with it differently.

* If the authorisation logic doesn't exist, it ignores.
* If the authorisation succeeds, no change.
* If the authorisation fails, the page should either display 401 page or redirect to somewhere for authentication.

**Comment by chinarosesz** [comment]
Sounds like a good plan. 

I was thinking about adding a middleware to check if the endpoint is swagger ui or json, redirect to the login page.  Looks like your flow is similar so I'll wait for this instead of implementing the middleware myself. I honestly don't know if my approach is going to work.

**Comment by justinyoo** [comment]
Yeah, I also considered the middleware approach.

However, we can't rely on the middleware because, unlike ASP.NET Core app, Azure Functions app runs either as a static way or IoC way.

**Comment by chinarosesz** [comment]
Thanks Justin for doing this. Excited to see this in the next preview release.

**Comment by justinyoo** [comment]
@chinarosesz The latest release, 0.9.0-preview includes this implementation. And here's the [doc](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md#further-authentication-and-authorisation).

**Comment by chinarosesz** [comment]
@justinyoo , do you know if this feature is available for out of process? The reason I'm asking is because we have a dev that tried to follow the documentation and she's unable to get it to show anything that would pop up a dialog to log in via AAD. Or maybe we are using this incorrectly?
