### ISSUE TITLE
SwaggerUI - Configure default client_id and scopes for OpenIdConnect authentication

### ISSUE THREAD

**Issue by ianc1** [Azure/azure-functions-openapi-extension#240]
Is there a way to set a default `client_id` and `scopes` for the OpenIdConnect authentication in the UI?

I.e like you can in Swashbuckle using:

```
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    options.OAuthClientId("demo_api_swagger");
});
```
<img width="825" alt="authentication-ui" src="https://user-images.githubusercontent.com/25267610/132958200-f36e2b38-5c45-40e5-93d3-5c31299ad216.png">

**Comment by justinyoo** [comment]
@ianc1 Thanks for the issue!

You can set up by following this [doc](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#openapisecurityattribute).

In addition to that, this #223 might help you configure your `OpenApiSecurity(...)` decorator.

**Comment by ianc1** [comment]
@justinyoo Thank you for the docs. 

I have been configuring the scopes by defining them in `OpenApiOAuthFlow.Scopes` as described in the doc but the issue I'm having is that I want to be able to enable the scopes by default in the SwaggerUI Auth dialog rather than rely on the user doing it. I've also tried duplicating the scopes in the OpenApiSecurity attribute but that didnt result in the scopes being enabled in the auth dialog. I have to manually tick/check each scope.


I also want to be able to do the same with the `client_id`. I.e I want to pre-populate the client_id field in the SwaggerUI auth dialog with my id by defaut so that the user does not need to enter it each time.

Thanks for your help!
```
    public class AzureADAuth : OpenApiOAuthSecurityFlows
    {
        public AzureADAuth()
        {
            this.Implicit = new OpenApiOAuthFlow()
            {
                AuthorizationUrl = new Uri("https://login.microsoftonline.com/mytenant/oauth2/v2.0/authorize"),
                Scopes = { { "profile", "read your profile information" }, { "email", "read your email address" } },
            };
        }
    }

[OpenApiSecurity(nameof(AzureADAuth), SecuritySchemeType.OAuth2, Flows = typeof(AzureADAuth), OpenIdConnectScopes = "profile,email")]

```

**Comment by justinyoo** [comment]
@ianc1 From the Swagger UI perspective, it's just a test harness and it doesn't show up your client ID and pre-ticked scopes by default.

If you want to provide a pre-populated client ID, then you can try the approach referred from [this doc](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#swagger-ui-customisation) to embed a custom JavaScript file, and it will give you some hints.
