### ISSUE TITLE
Links referring to moved documentation in readme.md

### ISSUE THREAD

**Issue by cjakobsen** [Azure/azure-functions-openapi-extension#241]
2 links in the _**Getting Started**_ section of readme.md is referring to moved documentation. They should be changed to point to the new location.

The links are:
- Enable OpenAPI documents to your Azure Functions HTTP Trigger (Preview)
- Microsoft.Azure.WebJobs.Extensions.OpenApi

**Comment by justinyoo** [comment]
@cjakobsen Thanks for pointing out! While I mostly agree with that, I would remain pointing the same document.

Instead, I would provide two links &ndash; in-proc.md and out-of-proc.md in the document, https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/enable-open-api-endpoints.md

The same goes applied to this page. https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md
