### ISSUE TITLE
Configurable url for /api/oauth2-redirect.html endpoint behind FrontDoor

### ISSUE THREAD

**Issue by lecamarade** [Azure/azure-functions-openapi-extension#244]
Hi,

We use Azure Funtion app behind FrontDoor. This adds complication of url rewrites.

The swagger url for the function app is: 
https://myapp.azurewebsites.net/api/swagger/ui

With FrontDoor it becomes:
https://mycompany/api/myapp/swagger/ui

The generated oauth2 redirect is
https://mycompany/api/oauth2-redirect.html 
instead of
https://mycompany/api/myapp/oauth2-redirect.html 

Can we modify the prefix for the redirect url to match the path expected by FrontDoor?

**Comment by justinyoo** [comment]
@lecamarade Thanks for the issue! Wonder whether you've found this doc or not: https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#overriding-base-urls

**Comment by lecamarade** [comment]
@justinyoo , Thank you for the link, yes I did find it.
It only helps to fix the CORS issue. Unfortunately, the url there is ignored by the code that updates the oauth2-redirect.html url in swagger-ui.js

The library adds prefix that comes from HttpSettings.RoutePrefix = "api".

From swagger-ui-bundle.js:
.call(t,window.location.host,"[[SWAGGER_UI_API_PREFIX]]/oauth2-redirect.html"),

[[SWAGGER_UI_API_PREFIX]] gets replaced by RoutePrefix from above. That's separate from the base url mentioned in the docs.

**Comment by lecamarade** [comment]
@justinyoo, please upate the labels. This is not a question and it is not resolved.

**Comment by justinyoo** [comment]
Let me take a further look.

**Comment by lecamarade** [comment]
@justinyoo , any updates on this one?
