### ISSUE TITLE
OpenApiResponseWithBody - Does not handle classes with IImmutableList

### ISSUE THREAD

**Issue by torepaulsson** [Azure/azure-functions-openapi-extension#245]
Hi,
This is really a great extension, just tried it out and will use it on all the azure functions we have! I noticed that there was a problem rendering the response body of a class when it has a property type of IImmutableList. I tried changing to IList and that works fine.

```csharp
public class ResponseDto{
   public ImmutableList<some class> List {get;}
}
```
renders just an empty class like so:
```json
{
   "list": {}
}
```

It would be great to add support for IImmutableList!

**Comment by justinyoo** [comment]
@torepaulsson Thanks for the issue! I'll take a look.

**Comment by justinyoo** [comment]
@torepaulsson I hope this PR #247 sorts out your issue. Please wait for the 0.9.0-preview release!

**Comment by torepaulsson** [comment]
That was very quick, thank you!
