### ISSUE TITLE
Add OpenAPI spec to build output

### ISSUE THREAD

**Issue by jeromekol** [Azure/azure-functions-openapi-extension#249]
Currently, it's only possible to use the provided cli or by running the function to get the openapi document.

It would be great, if you could provide a MsBuild target/task as part of the nuget package which generates the specification during build.

Maybe an option in csproj `<GenerateOpenApi>true|false</GenerateOpenApi>` could to be added to opt-in or opt-out.

Are there any plans in this direction?

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.
