### ISSUE TITLE
When using an object list, an object schema is generated.

### ISSUE THREAD

**Issue by Lee-WonJun** [Azure/azure-functions-openapi-extension#272]
**Describe the issue**
Using a list of object (base object) generates an object reference.

I recently cleared iusse ( #108 ) (PR no. 234).

I found a new bug (probably...) with object references.

Using a list of objects generates an object reference.

Fortunately, the item type is seems to be correct

```
"items": {
   "type": "object"
}
```

However,  schemas contains object type schema.

**To Reproduce**
1. I worte code like this

```csharp
class NoBaseObject
{

}
class ContainListObject
{
    public List<NoBaseObject> NoBaseObjectMembers { get; set; }
    public NoBaseObject NoBaseObjectMember { get; set; }

    //public List<object> BaseObjectMembers { get; set; }
    public object BaseObjectMember{ get; set; }
}

// some attributes..
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(ContainListObject), Summary = "successful operation", Description = "successful operation")]
public async Task<HttpResponseData> blahblah~~

```

2. check schemas

```
"components": {
    "schemas": {
        "containListObject": {
            "type": "object",
        "properties": {
                "noBaseObjectMembers": {
                    "type": "array",
            "items": {
                        "$ref": "#/components/schemas/noBaseObject"
            }
                },
          "noBaseObjectMember": {
                    "$ref": "#/components/schemas/noBaseObject"
          },
          "baseObjectMembers": {
                    "type": "array",
            "items": {
                        "type": "object"
            }
                },
          "baseObjectMember": {
                    "type": "object"
          }
            }
        },
      "noBaseObject": {
            "type": "object"
      },
      "object": {
            "type": "object"
      }
    },
    "securitySchemes": {
      /blah blah~~~~
    }
}
```

**Expected behavior**
There should be no "object" schema.

![image](https://user-images.githubusercontent.com/10369528/136391662-0afd7995-c638-4a7f-9d2b-de577664090a.png)

**Environment (please complete the following information, if applicable):**
 - OS: Windows
 - Browser firefox

**Additional context**
I also wondering about that this schema is correct in  "baseObjectMembers"
```
"items": {
   "type": "object"
}
```

**Comment by justinyoo** [comment]
There are a few methods in `TypeExtensions` and `OpenApiPaylodAttribute` that sort out this issue, I suspect. I think with your previous `BaseObjectTypeVisitor` PR approach would help.
