### ISSUE TITLE
OpenApiRequestBody with bodyType with recursive properties throws StackOverflowException.

### ISSUE THREAD

**Issue by decocsa** [Azure/azure-functions-openapi-extension#282]
**Describe the issue**
An OpenApiRequestBody with a bodyType of EditListRequestBody (see screenshots) throws StackOverflowException.
I think Feature/#156 fixed this for the OpenApiResponseWithBody, but not for the OpenApiRequestBody.

**Screenshots**
![image](https://user-images.githubusercontent.com/92383297/137277239-171f3f3c-4fb2-4eff-a896-cf7af97cdfc9.png)
![image](https://user-images.githubusercontent.com/92383297/137277300-0da75815-94e2-45d8-bc86-157f242214ea.png)

 - OS: Windows 10

**Comment by justinyoo** [comment]
@decocsa I'll close this issue for now. If you still have the same issue even after the suggestion by @level120, please leave a comment.
