### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by svrooij** [Azure/azure-functions-openapi-extension#283]
**Describe the issue**

The CLI in [this folder](https://github.com/Azure/azure-functions-openapi-extension/tree/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI) seems like a really good candidate to be a [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) that would make distributing it really easy (just publish a new version of a special nuget package).

Packaging a dotnet core cli app as a tool is just a matter of changing the top property group for the project file to:

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>azfuncopenapi</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>azfuncopenapi</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>
```

And running `dotnet pack` in the project folder. And before publishing it to nuget you can install it by running `dotnet tool install --global --add-source ./nupkg azfuncopenapi` from the project folder, as described [here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-use)

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.

**Comment by svrooij** [comment]
@justinyoo The use case of having a dotnet tool wasn't only the Github actions. Personally I hate GitHub actions that you cannot easily execute on your local machine, it excludes others that don't use GitHub actions (eg. Jenkins/GitLab/Azure DevOps). It also stops the other use cases like, we would like to generate the openapi.json right in Visual studio, and push it to some folder. (And then re-generate our typescript client that is used in a SPA.)

We are also considering serving the static file and not have it generate the openapi.json at runtime, for this to happen we would like to generate the file locally as well.

This would be easily accomplished by having a dotnet tool to do this, and not force it to be a GitHub Action. They can exist at the same time, it won't bite.

**Comment by justinyoo** [comment]
I understand your current pain point.

I will provide a Power Shell script and/or bash script that you can run on any CI/CD pipeline, in the meantime. I think the script can be injected to your .csproj file.

Currently, the existing CLI project is not really scalable, which needs to be thoroughly reviewed.
