### ISSUE TITLE
Feature request: Parameter collectionFormat = multi

### ISSUE THREAD

**Issue by AndersRod** [Azure/azure-functions-openapi-extension#290]
**Describe the request**
OpenAPI array parameters can have [collectionFormat of type `csv`, `ssv`, `tsv`, `pipes` and `multi`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#parameter-object). 

To my understanding, Azure-functions-openapi-extension currently only supports delimiter types for `OpenApiParameter`. 

Please add support for `multi` type.

**Comment by justinyoo** [comment]
@AndersRod Thanks for the suggestion! This extensions is designed based on the OpenAPI spec v3.0.1, and this is [the spec for the parameter object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#parameter-object). Unfortunately, your link is pointing to the v2.0 spec.

I'm sure that I've implemented the parameter object spec based on the v3.0.1.
