### ISSUE TITLE
TypeLoadException when trying to load QueryCollection in .NET 5/.NET 6 isolated function if Microsoft.AspNetCore.Authentication.JwtBearer is referenced

### ISSUE THREAD

**Issue by AieatAssam** [Azure/azure-functions-openapi-extension#296]
Versions **0.9.0-preview** and **1.0.0** of Microsoft.Azure.Functions.Worker.Extensions.OpenApi introduced an issue into .NET5/.NET6 isolated functions which reference Microsoft.AspNetCore.Authentication.JwtBearer  (5.0.11) when trying to render swagger UI:
```
[2021-10-22T15:15:40.622Z] System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerUI. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
)
[2021-10-22T15:15:40.624Z]  ---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[2021-10-22T15:15:40.626Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions.OpenApiHttpRequestDataExtensions.Queries(HttpRequestData req)
[2021-10-22T15:15:40.627Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.HttpRequestObject..ctor(HttpRequestData req)
[2021-10-22T15:15:40.630Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Functions.OpenApiTriggerFunction.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)
[2021-10-22T15:15:40.631Z]    at Microsoft.Azure.Functions.Worker.Extensions.OpenApi.DefaultOpenApiHttpTrigger.RenderSwaggerUI(HttpRequestData req, FunctionContext ctx)

```
The issue manifests itself the moment **Microsoft.AspNetCore.Authentication.JwtBearer** is referenced and goes away when the reference is removed.

Version 0.8.1-preview does not exhibit the problem.

Looks like a problem might be with the fact that QueryCollection definition is located in _Microsoft.AspNetCore.Http.Internal_ namespace in .NET Standard 2.0 implementation and in _Microsoft.AspNetCore.Http_ namespace in .NET 5. Possibly introduction of **Microsoft.AspNetCore.Authentication.JwtBearer** package brings along .NET 5 explicit dependency to **Microsoft.AspNetCore.Http.dll**

Minimum replication project is attached.
[QueryCollectionIssueReproduction.zip](https://github.com/Azure/azure-functions-openapi-extension/files/7399622/QueryCollectionIssueReproduction.zip)

I can now confirm that version 1.0.0 still exhibits this issue. Furthermore, both .NET 5 and .NET 6 are affected.

**Comment by antoniodlp** [comment]
+1 I also have the trick enabled and it did not help

**Comment by PanosKousidis** [comment]
I just came across this issue as well.
For me it was the reference of package Microsoft.Azure.AppConfiguration.AspNetCore that caused the same error.

**Comment by markusschweitzer** [comment]
Same here with net6

**Comment by antoniodlp** [comment]
These packages cause problems too:
- Microsoft.AspNetCore.SpaServices
- Microsoft.AspNetCore.SpaServices.Extensions

**Comment by r0ss88** [comment]
@justinyoo Hi Justin, @AieatAssam provided a fix for this 25 days ago. It would be great if the PR could be reviewed and approved please :).

**Comment by AieatAssam** [comment]
@justinyoo I have an open PR #318 that resolves this with minimal changes. Any chance this can be reviewed? We are still unable to upgrade because of this issue.

**Comment by dianepanagiotopoulos** [comment]
+1 

My project has a dependency on Microsoft.AspNetCore.Authentication.JwtBearer, as well as a dependncy on a project with Microsoft.Extensions.Logging.Abstractions (as in #281 ). I tried putting the workaround in the csproj files for both projects but am still unable to render the swagger UI.

**Comment by RomanAlberdaSoftserveInc** [comment]
I'm still having this issue.

**Comment by AieatAssam** [comment]
> I'm still having this issue.

It's been tagged as version 1.1.0, so I'd assume we need to wait for release 1.1.0 to come out. You can always build it locally and verify. If you are talking about build from source that still exhibits the issue, post some details please so it can be reviewed further.
