### ISSUE TITLE
Select naming strategy when using the CLI

### ISSUE THREAD

**Issue by basilfx** [Azure/azure-functions-openapi-extension#304]
**Describe the issue**
The CLI does not have an [option](https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Program.cs#L47-L52) to override the naming strategy. That would be useful to have.

**To Reproduce**
N/a

**Expected behavior**
Naming strategy selectable via an additional command line flag or global setting. I cannot find another way to set it globally.

**Screenshots**
N/a

**Environment (please complete the following information, if applicable):**
* OS: macOS 12.0.1
* .NET SDK 5.0.402
* 0.9.0-preview (from source)

**Additional context**
N/a

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.
