### ISSUE TITLE
redirect_url is incorrect, as it is missing a forward slash between host and route prefix

### ISSUE THREAD

**Issue by MikeChristensen** [Azure/azure-functions-openapi-extension#307]
**Describe the issue**
OAuth redirect URLs are incorrect due to a bug in SwaggerUI::AddServer().  This bug was introduced in 0.9.0 by [Pull Request 253](https://github.com/Azure/azure-functions-openapi-extension/pull/253).

**To Reproduce**

1. Create an HTTP trigger with an OAuth flow:

```
[OpenApiSecurity("Limeade_Identity", SecuritySchemeType.OAuth2, Flows = typeof(LimeadeIdentitySwaggerOAuthFlows))]
public async Task<IActionResult> SampleTriggerAsync([HttpTrigger(AuthorizationLevel.Function, "GET", Route = null)] HttpRequest req) ...
```

2. Go to the Swagger UI at /api/swagger/ui and click the "Authorize" button.
3. Type in a client_id (doesn't matter what) and click Authorize

Result:

Redirect URL contains:

```
&redirect_uri=http%3A%2F%2Flocalhost%3A7071api%2Foauth2-redirect.html
```

In other words, it's trying to redirect back to localhost:7071api/oauth2-redirect.html instead of localhost:7071/api/oauth2-redirect.html

**Expected behavior**
The "redirect_url" parameter should combine the host and route prefix correctly.

**Additional context**
I've pulled down the code and changed SwaggerUI::AddServer() to the following:

```
absolutePath = new Uri(this._baseUrl).AbsolutePath; //.Trim('/');
this._swaggerUiApiPrefix = absolutePath;
```

(Basically, I commented out the part that trims off the trailing frontslash on the base URL).  I built that DLL and copied it over the NuGet version, and this makes the error go away.

There doesn't appear to be a workaround I can use until this bug is fixed, since _swaggerUiApiPrefix is private so I can't fix it, and AddServer is not virtual so I can't override it.  I'm hoping we can fix this issue ASAP!

**Comment by justinyoo** [comment]
@MikeChristensen Thanks for the issue! I was able to reproduce this issue on my end. I'm working on it!
