### ISSUE TITLE
Where does the Open API CLI live?

### ISSUE THREAD

**Issue by johnnyreilly** [Azure/azure-functions-openapi-extension#314]
According to the docs here:

https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-cli.md

> The CLI is available for download at GitHub. It's always tagged with cli-<version>. Download the latest version of CLI.
>
> Linux: azfuncopenapi-v<version>-netcoreapp3.1-linux-x64.zip 
> MacOS: azfuncopenapi-v<version>-netcoreapp3.1-osx-x64.zip
> Windows: azfuncopenapi-v<version>-netcoreapp3.1-win-x64.zip

I've looked on the releases page but I can't find `azfuncopenapi-v1.0.0-netcoreapp3.1-osx-x64.zip` or similar... Could you direct me to it please?

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.
