### ISSUE TITLE
Custom css in OpenApiCustomUIOptions

### ISSUE THREAD

**Issue by FirebladeDan** [Azure/azure-functions-openapi-extension#316]
**Describe the issue**
Does this actually work? In your samples you have dist/custom.css. but as the name of the file you have dist.custom.css. 

**To Reproduce**
1. Create dist directory in function app
2. Create "custom.css" file in dist directory
3. Create OpenApiCustomUIOptions.cs file in Configurations directory
4. In file above, set CustomStylesheetPath to "custom.css"
5. In csproj: ItemGroup EmbeddedResource Include="dist\custom.css" ItemGroup

**Expected behavior**
I expected it to work but naming looks botched. Can you confirm file name and configuration please?

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment (please complete the following information, if applicable):**
 - OS: [e.g. Windows/Mac/Linux]
 - Browser [e.g. edge, chrome, firefox, safari]

**Additional context**
I copied this: https://github.com/Azure/azure-functions-openapi-extension/tree/main/samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static
and followed this:
https://www.youtube.com/watch?v=hC44iF0luR0&t=1915s

It didn't work for me

**Comment by FirebladeDan** [comment]
I was able to make it work but still leaves me with having to serve my css :/.

public override async Task<string> GetStylesheetAsync()
        {
            using var client = new HttpClient();
            var response = await client.GetAsync(CustomStylesheetPath);
            if (response.IsSuccessStatusCode)
            {
                var content = response.Content;
                return await content.ReadAsStringAsync();
            }
            return string.Empty;
        }

**Comment by justinyoo** [comment]
@FirebladeDan Thanks for the issue! If you want to embed custom CSS and JavaScript files, you should do this way:

```csharp
public override string CustomStylesheetPath { get; } = "dist.my-custom.css";
public override string CustomJavaScriptPath { get; } = "dist.my-custom.js";
```

Please make sure that the filename is `dist.my-custom.css`, not `my-custom.css`.
