### ISSUE TITLE
NullReferenceException in RenderSwaggerDocument with simplest Function HttpTrigger

### ISSUE THREAD

**Issue by phil-allen-msft** [Azure/azure-functions-openapi-extension#33]
Following the guide at https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/enable-open-api-endpoints.md

1. Create the functions project, add the HttpTrigger, make changes to host.json and add the OpenApi* attributes as listed to the HttpTrigger.
2. Run the func.exe locally
3. Try to browse to the [localhosturl]/swagger/ui page

RESULT:
NullReferenceException in a call to Linq (SelectMany related)

EXPECT:
The page to render with the one HttpTrigger listed.

**Comment by justinyoo** [comment]
Thanks @phil-allen-msft It's fixed and waiting for the hotfix release.
