### ISSUE TITLE
File not found for empty folder when using WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by laurens1984** [Azure/azure-functions-openapi-extension#332]
#### Investigative information

- Timestamp: 2021-11-26T13:11:58.9505949Z
- Function App version: v4
- Function name(s) (as appropriate): Functions.RenderSwaggerDocument
- Invocation ID: 9b9ac677-d60b-446d-8623-228acef8f606
- Region: West Europe

#### Repro steps

The Function App gets build with 'dotnet publish', in the resulting file structure there is a folder that is empty named 'nl'. The file structure gets zipped. We publish the zip file to Azure with Azure DevOps, but publishing from Visual Studio 2022 gives the same result. Our Azure Functions instance is configured with WEBSITE_RUN_FROM_PACKAGE with value 1.

Our Functions App uses Microsoft.Azure.WebJobs.Extensions.OpenApi version 1.0.0. We call the endpoint to render the Swagger UI and get the following stacktrace:
```
could not find file 'D:\home\site\wwwroot\nl'.

   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.DirectoryFinished()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.GetRuntimeFilenameAsync(String functionAppDirectory)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTriggerContext.SetApplicationAssemblyAsync(String functionAppDirectory, Boolean appendBin)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Extensions.OpenApiHttpTriggerContextExtensions.AuthorizeAsync(Task`1 context, IHttpRequestDataObject req)
   at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiTriggerFunctionProvider.RenderSwaggerUI(HttpRequest req, ExecutionContext ctx, ILogger log)
```

When I open the Kudu site for the Azure Functions instance and open CMD and go to the folder 'D:\home\site\wwwroot\nl' and use 'dir' I get the output:
```
 Volume in drive D is Windows
File Not Found
 Volume Serial Number is B492-AC54

 Directory of D:\home\site\wwwroot\nl
```

This makes me think the issue is not with Microsoft.Azure.WebJobs.Extensions.OpenApi.

#### Expected behavior

That empty folders are readable.

#### Actual behavior

The empty folder is not found.

#### Known workarounds

Remove all empty folder before publishing to Azure Functions.

#### Related information 

<details>
<summary>Source Microsoft.Azure.WebJobs.Extensions.OpenApi</summary>

[azure-functions-openapi-extension/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs](https://github.com/Azure/azure-functions-openapi-extension/blob/90a44bb441049d9c21ed6ee06aafb1ddd4e24844/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiHttpTriggerContext.cs#L259)

Think the line giving the error is the below one.
```csharp
var files = Directory.GetFiles(functionAppDirectory, "*.deps.json", SearchOption.AllDirectories);
```
</details>

**Comment by v-bbalaiagar** [comment]
Transferred this issue to openapi repo for further investigation.

**Comment by Joeghanoe** [comment]
Hi I am using a near identical configuration as @laurens1984 and receiving the following error at runtime:

`Could not find file 'C:\home\site\wwwroot\runtimes\win-x64\native'.`

Our app is also deployed using an Azure CI/CD pipeline and experiencing the same issue. is there possibly an issue you could refer us to in the openapi repo @v-bbalaiagar ?

**Comment by sammeidroid** [comment]
Had a similar problem with deployment via Azure pipeline. 
In the deployment task "AzureFunctionApp@1" I change the "deploymentMethod" from 'runFromPackage' to 'zipDeploy'.
After that it worked.

See here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#zip-deploy

**Comment by havarnov** [comment]
@sammeidroid note that this work-around might come with its own issues.

E.g. this describes one issue with 'zipDeploy', see https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package:
> All other deployment methods in App Service have something in common: your files are deployed to D:\home\site\wwwroot in your app (or /home/site/wwwroot for Linux apps). Since the same directory is used by your app at runtime, it's possible for deployment to fail because of file lock conflicts, and for the app to behave unpredictably because some of the files are not yet updated.

**Comment by justinyoo** [comment]
I don't think this is relevant to this extension. Closing.

**Comment by yoozek** [comment]
@justinyoo IMHO it is relevant to the extension, because it is not working if there is an empty folder in a published app.
I had the same issue with the 'de' folder. Build moves *.resources.dll packages from /de to /bin/de and leaves an empty folder.

Changing the deployment method works, but it causes scalability issues.

As a workaround, I remove empty folders after release
