### ISSUE TITLE
OpenAPI UI dll load failure from release pipeline only when test project is included in build

### ISSUE THREAD

**Issue by ssunkari** [Azure/azure-functions-openapi-extension#333]
**Describe the issue**
When Azure function project with an nunit test project is build and published to Azure app service. I get below error
Could not load file or assembly 'D:\home\site\wwwroot\bin\Demo.Fn.Tests.dll'. The system cannot find the file specified.

However I have observed if the test project is removed from the solution swagger UI loads fine. I'm assuming document generation is scanning solution file and complaining about the test projects since they are included in sln file. 

I'm using Azure functions v3, Microsoft.Azure.WebJobs.Extensions.OpenApi v1.0.0.
App deployed to Azure App Services. 

Bizarrely swagger UI loads fine when run locally from VisualStudio. 

Can you please advise if there is any activity happening around this problem, I have seen similar issue reported else where 
https://githubmemory.com/repo/Azure/azure-functions-openapi-extension/issues/196

**Comment by justinyoo** [comment]
@ssunkari Thanks for the issue! It's a known one. Please refer to #306 in the meantime.

**Comment by justinyoo** [comment]
Related to #196
