### ISSUE TITLE
Support for IDocumentFilter

### ISSUE THREAD

**Issue by ThomasBleijendaal** [Azure/azure-functions-openapi-extension#340]
With other Swagger / OpenApi systems it used to be possible to implement something like an `IDocumentFilter` and have the possibility to modify the document before it is rendered. I want to switch to this package as it has support for the newer Azure Function runtimes, but I kinda need the functionality of an `IDocumentFilter`. For example, I use that filter for modifying the path of an http function, as I use the swagger document to generate ARM templates for Azure API Management.

Is this something that is on the roadmap, or desirable at all? 

I would imagine to allow for configuring something of a `IDocumentFilter` in either DI or some configuration object, and have the functions like https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi/OpenApiTriggerFunctions.cs#L59 use those filters after generating the `IDocument` and right before calling `RenderAsync`. 

If it sounds like a good idea I would give it a try and open a PR. I haven't looked into every detail yet, so perhaps its a bit more complicated that what I describe above.

**Comment by morrisonbrett** [comment]
I need this too. Because of the limitations of how the `app.Swagger()` is not available in the Azure Function startup harness, we need more ability to implement interfaces such as `IOpenApiConfigurationOptions`.
