### ISSUE TITLE
Auto-generate swagger.json 

### ISSUE THREAD

**Issue by jvmlet** [Azure/azure-functions-openapi-extension#342]
Would  you please provide the sample of how to auto-generate `swagger.json`  **during build** to use it  for clients/dtos  bindings generation for different languages later.
I see `Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI` project that looks like  doing exactly this, but it's not published as nuget package.
Thanks

**Comment by wis3guy** [comment]
I second that request, as we need the _static_ file to be present for NSwag to generate our clients during CI/CD.

**Comment by jvmlet** [comment]
@wis3guy I bypass this limitation by running the function locally (during CI build) with docker compose and azurite container. Then I provide `http://myapp/api/swagger.json` to NSwag.

**Comment by StefanSchoof** [comment]
This sound very similar to #58

**Comment by justinyoo** [comment]
@jvmlet Thanks for the issue! Yes, we're aware of that, but it's de-priotised over other issues. Let's keep this open for further discussion.

**Comment by justinyoo** [comment]
Related: #343

**Comment by justinyoo** [comment]
As the PR, #489, has been merged, you can generate the OpenAPI doc on-the-fly, within the GitHub Actions workflow.
