### ISSUE TITLE
Object schema Description attribute

### ISSUE THREAD

**Issue by bteamsoftware** [Azure/azure-functions-openapi-extension#345]
I'm being asked to migrate an API from an azure app service API to an Azure Functions app. In a traditional API, it's possible to have the &lt;summary&gt; comment from a class definition to appear as a Description attribute for the object schema in the Open API document. Is this possible to do with the extension? I've searched through the code samples and tried searching through the code but haven't been able to find anything.

``` json
{
	"openapi": "3.0.1",
	"info": {
	  "title": "Mapping API",
	  "version": "v1"
	},
	"paths": {
	},
	"components": {
	  "schemas": {
		 "GeoAsset": {
			"type": "object",
			"properties": {
			  "type": {
				 "type": "string",
				 "nullable": true,
				 "readOnly": true
			  },
			  "geometry": {
				 "$ref": "#/components/schemas/GeoPoint"
			  },
			  "properties": {
				 "$ref": "#/components/schemas/AssetProperties"
			  }
			},
			"additionalProperties": false,
			"description": "Represents a single asset in GeoJSON format."
		 }
	  }
	}
 }
```
The example provided above has a "description" attribute. That text comes from a &lt;summary&gt; on the class:

``` c#
/// <summary>
/// Represents a single asset in GeoJSON format.
/// </summary>
public class GeoAsset : GeoFeature<GeoPoint, AssetProperties>
{
}

```

**Comment by theplankmeister** [comment]
I'm in the same situation. This is a very desirable feature in a few of our APIs.

**Comment by justinyoo** [comment]
@bteamsoftware Thanks for the issue! Currently, we don't have plan to support the XML comment feature.
