### ISSUE TITLE
OpenAPI functions RenderOAuth2Redirect, RenderOpenApiDocument, RenderSwaggerDocument, and RenderSwaggerUI missing when published to folder

### ISSUE THREAD

**Issue by gitmadness** [Azure/azure-functions-openapi-extension#347]
Published my function app to a folder so I can zip it and put it on a share and I noticed that the functions created by Microsoft.Azure.WebJobs.Extensions.OpenApi are not there.  I see the functions when debugging. 

Did I miss a step somewhere?

Using V3 Functions SDK and VS2019.

**Comment by JohnGe0rge** [comment]
Hi there, I am also rather confused by this.

When running via debug, the additional `RenderOAuth2Redirect`, `RenderOpenApiDocument`, `RenderSwaggerDocument`, and `RenderSwaggerUI` endpoints _are_ present.

When publishing the Azure Function (via func tasks in VSCode) it does deploy successfully however as @gitmadness has noted our shiny OpenAPI pages got lost somewhere.

Assuming that it might be some hidden magic, I have tried visiting;

- `{functionUri}/swagger.json?code={code}`
- `{functionUri}/swagger/swagger.json?code={code}`
- `{functionUri}/swagger/ui?code={code}`

..all to no avail.

Justin Yoo over at MSFT has created some extensions to allow publishing of these _as_ functions but I am not sure whether these work with the current landscape we're using (dotnet6, inproc, v4 runtime - posting this primarily for @gitmadness's benefit as this may help them).

- Blog post describing the implementation: https://devkimchi.com/2019/02/02/introducing-swagger-ui-on-azure-functions/
- Repository containing the libs: https://github.com/aliencube/AzureFunctions.Extensions

I have run into some implementation issues with the above, like `GetSpecVersion()` and `GetExtension()` methods, these are used in the example without any prefixes; suggesting they should be present in the example somewhere, but aren't, nor can I find them in the assembly anywhere. Some more search-fu later and I landed on this github issue.

**Comment by JohnGe0rge** [comment]
Ok so I made some headway on this, started a fresh test project using the `AlienCube` nuget mentioned previously and got it working quite happily.

- Dotnet 6 IoC, v4 runtime
- Builds ok
- Debugs locally ok with all the right endpoints
- Deploys to Azure FunctionApp ok
- Has all the right endpoints published, and they all work

To be brutally honest with myself I just RTFM with a fresh test project and it worked 🤷 I think my test yesterday must have had some conflicting config from all the headscratching trying to get it working.

Given the nature of the lineage of these nugets, I tried porting the same working config to use the `Microsoft.Azure.Functions.Worker.Extensions.OpenApi` nuget, all works flawlessly... **apart from no OpenApi Functions published to the Function App** on deployment.

No offense to anybody, but I suspect the current release here is borked. With the above workaround it's no biggie (for me) now though - and porting the same config to this repo's way of doing it is actually quite trivial, technical debt can be paid off at some point with a single paycheque 😁 

@gitmadness feel free to give me a yell if you can't get the `AlienCube` way of doing it working, happy to help.

**Comment by justinyoo** [comment]
@gitmadness @JohnGe0rge Thanks for the issue! I assume that you're using "in-proc" worker of Azure Functions app, by using the `Microsoft.Azure.WebJobs.Extensions.OpenApi` package. Because it's the characteristics of the "in-proc" worker, those endpoints are showing up on your local machine, but they're hidden (encapsulated) when deployed to Azure.

Just FYI &ndash; The `Aliencube` one is no longer maintained, and this official extension has more features than that.
