### ISSUE TITLE
How to read API definitions from generated XML Documentation

### ISSUE THREAD

**Issue by SyntaxWarrior** [Azure/azure-functions-openapi-extension#348]
**Describe the issue**
I've used swagger/OpenAPI quite a bit before and have set it up so that it automatically documents my methods. I want to achieve the same thing here and not have to decorate a method. I want it to provide a base by itself (which I can later improve if I want to). 

Previously this was achieved with 
![bild](https://user-images.githubusercontent.com/23475688/150408005-41851e69-1562-412d-a020-9d22d920877e.png)
and pointing OpenAPI to that file. 

**To Reproduce**
>Create new project, 
>Install Microsoft.Azure.Functions.Worker.Extensions.OpenApi
>Run

**Expected behavior**
The template function should be present in the documentation along with its paramaters and return type.

I tried to direct OpenApi to the generated xml file but I have not been successful. Don't know if the support is missing or if I'm doing it wrong.

**Screenshots**
This is what I'm seeing. 
![bild](https://user-images.githubusercontent.com/23475688/150408280-353111dd-a59b-4e7f-93b3-6cd0ffec7ae7.png)

Expected this to be listed: 
![bild](https://user-images.githubusercontent.com/23475688/150408609-2ef425ff-9da4-43be-9fb1-f2787936b80f.png)

**Environment (please complete the following information, if applicable):**
 - OS: Win 10
 - VS 2022

**Comment by SyntaxWarrior** [comment]
In the old Azure functions you could use `AzureExtensions.Swashbuckle` and write
```
 builder.AddSwashBuckle(Assembly.GetExecutingAssembly(), opts =>
    {
        opts.XmlPath = "FunctionBlog.Definition.xml";
    });
```
and it would just work.

**Comment by tommck** [comment]
This is a really big deal for me. We use extensive XML documentation so that our generated OpenAPI UI has a ton of useful information for our clients. If we don't have that, we won't be able to use this otherwise perfect package!

**Comment by APIWT** [comment]
I started trying to go down this road as well, and ended up getting nervous for a couple reasons:
1) XML documentation is output as a build step, but I have no idea if it would be embedded into the package that will be uploaded to Azure.
2) Even if the XML documentation was part of the published package in Azure Functions, I'm not sure what the most reliable way to get the XML path would be. You could try to use `typeof(Whatever).Assembly` magic, but I feel like it'd be a little bit janky.

That being said, I ended up creating a set of packages that let me at least document example values for my response models. You can find that here, maybe it would be helpful:
- https://www.nuget.org/packages/OpenApiExampleAnnotations/
- https://www.nuget.org/packages/OpenApiExampleAnnotations.Attributes/
- Source: https://github.com/RealGoodAppsLLC/OpenApiExampleAnnotations
- Sample Usage(s):
   - https://github.com/RealGoodAppsLLC/OpenApiExampleAnnotations/blob/main/test/OpenApiExampleAnnotations.TestModels/TestResponseModel.cs
   - https://github.com/RealGoodAppsLLC/OpenApiExampleAnnotations/blob/main/test/OpenApiExampleAnnotations.TestFunctions/TestFunction.cs#L20

**Comment by justinyoo** [comment]
@SyntaxWarrior Thanks for the issue! Unfortunately, the auto-generation from XML comments is not something this extension offers, and it's not on the roadmap for now.

**Comment by SyntaxWarrior** [comment]
Then it makes my choice to not use Azure functions very easy, thank you :)
