### ISSUE TITLE
Overwriting Base URL

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#35]
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/136

> We're also using an Azure API Management Instance and Azure Front Door in front of our API which changes the base url, however on the Swagger UI this is still pointing to the original Azure Function URL, is there a way to override the baseUrl as well?

> Yeah adjusting the base URL would be pretty important for us, the Azure Function base URL is fairly different from the API Management base URL.

**Comment by justinyoo** [comment]
This has been released to [v0.4.0-preview](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.4.0-preview).

**Comment by disambiguationuk** [comment]
![image](https://user-images.githubusercontent.com/11738048/107553113-429cba00-6bcc-11eb-859c-c43ec90ff5b6.png)

Amazing, thanks so much!
