### ISSUE TITLE
OpenAPI not generating for routes contained in a separate project in the same solution

### ISSUE THREAD

**Issue by cdodrzywolski** [Azure/azure-functions-openapi-extension#351]
**Describe the issue**
We have a number of routes in our Functions App project that generate just fine when we call the openapi route (.../api/openapi/v3.json).

However we have another set of routes contained within a class library project, within the same solution, decorated in the same manner, that do not show up on the generated openapi spec. 

If I move one of the route classes from the class library into the function app then the openapi will generate for those routes.

**To Reproduce**
Get route in Function App project:
![image](https://user-images.githubusercontent.com/68967069/151407893-8c2219e3-6da6-4a9c-a254-efe7b546b832.png)

Get route in class library project:
![image](https://user-images.githubusercontent.com/68967069/151407998-65ab9245-0d91-4d15-86ba-a3abd9463f55.png)

Run locally, observe you can call both Get routes.
![image](https://user-images.githubusercontent.com/68967069/151408518-b0e4a7ac-5ccd-443b-80c0-32817e480ab4.png)
![image](https://user-images.githubusercontent.com/68967069/151408580-e3c6b02d-3d80-4913-a959-04588fc5d112.png)

Then call open API route (.../api/openapi/v3.json)
Only the Get route in the Function App project is displayed
![image](https://user-images.githubusercontent.com/68967069/151409132-c843d5eb-0553-4248-b02c-4f2f87496d07.png)

**Comment by cdodrzywolski** [comment]
Cool thanks!

**Comment by justinyoo** [comment]
As the issue is now resolved, this update will be released in the upcoming v1.2.0 release. Stay tuned! I'll close this issue for now.

FYI &ndash; the change is only applicable for out-of-proc worker (dotnet-isolated). The in-proc worker is not supported for now.

**Comment by cdodrzywolski** [comment]
Awesome thanks for looking at that!
