### ISSUE TITLE
Error OpenApiHttpTrigger.RenderSwaggerUI and my function have the same value for FunctionNameAttribute

### ISSUE THREAD

**Issue by amalea** [Azure/azure-functions-openapi-extension#353]
**Describe the issue**
Hello,

I'm using the OpenApi Extensions in a Azure Functions app, netcoreapp3.1.
My csproj contains:

```
<PropertyGroup>
             <TargetFramework>netcoreapp3.1</TargetFramework>
             <AzureFunctionsVersion>V3</AzureFunctionsVersion>
</PropertyGroup>
....
<ItemGroup>
	   <PackageReference Include="Aliencube.AzureFunctions.Extensions.OpenApi" Version="3.1.1" />
......
```

But when the Microsoft.Azure.WebJobs.Extensions.OpenApi NuGet package is included, the folder OpenAPI with 3 templates are also included in my project.
![image](https://user-images.githubusercontent.com/14162970/152150228-7681e0b0-3d4b-4966-ac82-3baa1c6ebbb3.png)

I have my own class OpenAPI, with RenderOpenApiDocument and RenderSwaggerUI (as they were used in an older project with openAPI version 1.5.4)

```
[FunctionName(nameof(RenderSwaggerUI))]
        [OpenApiIgnore]
        public static async Task<IActionResult> RenderSwaggerUI(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "swagger/ui")] HttpRequest req)
        {
            var ui = new SwaggerUI();
            var result = await ui.AddMetadata(InfoFromSettings)
                .AddServer(req, "v1")
                .BuildAsync()
                .RenderAsync("swagger.json")
                .ConfigureAwait(false);

            return new ContentResult
            {
                Content = result,
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK
            };
        }
```

When compiling I get this error:

> Function Aliencube.AzureFunctions.Extensions.OpenApi.OpenApiHttpTrigger.RenderSwaggerUI and _MyPackageHere_.OpenApi.RenderSwaggerUI have the same value for FunctionNameAttribute

How can I solve this? Why is that folder included in my project?
If I rename for ex.  RenderSwaggerUI, I will end up having 2 functions with different names pointing to the same URL :  http://........./v1/swagger/ui. 
My trigger has AuthorizationLevel.Anonymous so that I can render the swagger without the auth code. But when deployed in the Azure portal, having 2 functions, it loads Aliencube.AzureFunctions.Extensions.OpenApi.OpenApiHttpTrigger.RenderSwaggerUI which has AuthorizationLevel.Function.

When including the Nuget version 1.5.4 that folder wasn't included in my project and I could use the same names for RenderSwaggerUI and RenderOpenAPiDocument.
Now, when including Nuget 3.1.1  I can't use the same names.

Could you please help me with a solution?

Thank you!

**Comment by justinyoo** [comment]
@amalea Thanks for the issue! Could you please remove the NuGet package, `Aliencube.AzureFunctions.Extensions.OpenApi`, and build the app again? You don't need the `Aliencube.AzureFunctions.Extensions.OpenApi` package any longer, as its all features are transferred into this `Microsoft.Azure.WebJobs.Extensions.OpenApi` package.

**Comment by amalea** [comment]
Hello,

Thank you! I have replaced the old lib with the new one, but I have a struggling now with the authorization.
My HttpTrigger is AuthorizationLevel.Function.
Using the old lib, I had a 'function key' box where I could enter the function key (a function might have more keys).
With the new lib, I can use  [OpenApiSecurity("function key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)], but how to use this with multiple function keys? Is there any way of doing this without hardcoding the function key?

Thank you!
