### ISSUE TITLE
Generated swagger works locally, but is empty when deployed in Azure

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-openapi-extension#359]
**Describe the issue**
I leverage the `OpenApiOperation` attribute, and the related attributes, to describe several `HttpTrigger` functions in my netcoreapp3.1 Azure Functions project.
It works successfully, when I navigate to my local swagger endpoint: 'http://localhost:7071/api/swagger/ui', but when I have deployed it (through Github Actions), the generated Swagger on the endpoint 'https://mysite-tst.azurewebsites.net/api/swagger.json' is empty and does not contain operations.
The UI page indicates: No operations defined in spec!

**To Reproduce**
1. Add relevant attributes such as `OpenApiOperation`, `OpenApiSecurity`, `OpenApiResponseWithBody`... to functions that contain a `HttpTrigger` binding.
2. Run the Azure Functions project locally
3. Navigate to http://localhost:7071/api/swagger/ui - see relevant and correct Swagger UI
4. Deploy the Azure Functions project to Azure through CI/CD (using RELEASE version, zip deployment)
5. Navigate to https://mysite-tst.azurewebsites.net/api/swagger.json - see empty json file

```json
{
  "swagger": "2.0",
  "info": {
    "title": "OpenAPI Document on Azure Functions",
    "version": "1.0.0"
  },
  "host": "mysite-tst.azurewebsites.net",
  "basePath": "/api",
  "schemes": [
    "https"
  ],
  "paths": { }
}
```

**Expected behavior**
Swagger file should be the same , regardless of hosting environment

**Comment by justinyoo** [comment]
@SamVanhoutte Thanks for the issue! Do you happen to have a sharable GitHub repository that I can reproduce the same error on my end?

**Comment by SamVanhoutte** [comment]
@justinyoo thanks for reaching out
The actual build can be found here: 
https://github.com/SamVanhoutte/cotacol-strava-workers/blob/develop/.github/workflows/cd-test.yaml

The functions project (3.1.x core) is here: https://github.com/SamVanhoutte/cotacol-strava-workers/tree/develop/src/BikeXplorer.Workers

(not merged to master, so make sure you keep looking at develop branch)

**Comment by SamVanhoutte** [comment]
Hello @justinyoo 
Thanks to the suggestion of @RealGoodAnthony  , I changed my build so that the dotnet publish was not using the `.sln` , but was pointing to the specific `csproj` project file.  And that seemed to solve the problem. 

So, I did the following steps:

1. Created a copy of the .sln file and removed the test project from that
2. Updated the csproj file of the Test project to include the following line:
`<IsPublishable>false</IsPublishable>`
3. Changed the following line: 
`dotnet publish ${{ env.SOLUTION }} -c ${{ env.BUILD_CONFIG }} -o ${{env.DOTNET_ROOT}}/myapp`
to 
`dotnet publish ${{ env.WORKER_PROJECT }} -c ${{ env.BUILD_CONFIG }} -o ${{env.DOTNET_ROOT}}/myapp`
in my `.yaml` workflow
