### ISSUE TITLE
proxies.json still work?

### ISSUE THREAD

**Issue by ClumsyPenguin** [Azure/azure-functions-openapi-extension#372]
I am unable to get `proxies.json` to re-route my rendering url of swagger API

We run Azure functions (.NET6) with versions:
```
Azure Functions Core Tools
Core Tools Version:       4.0.3971 Commit hash: d0775d487c93ebd49e9c1166d5c3c01f3c76eaaf  (64-bit)
Function Runtime Version: 4.0.1.16815
```
Upon following the instructions found [here](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/shortening-swagger-ui-page-url.md).

I was not able to get the alternative path /swagger/ui working, it still only renders at /api/swagger/ui
![image](https://user-images.githubusercontent.com/22469147/155144813-6e5d7f36-62e1-47d0-9ee2-69bce954bdb4.png)

The json file reside in our root of the project itself.

proxies.json
```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "swaggerUI": {
      "matchCondition": {
        "methods": [ "GET" ],
        "route": "/swagger/ui"
      },
      "backendUri": "%OpenApi__BackendProxyUrl%/api/swagger/ui"
    },
    "swaggerDoc": {
      "matchCondition": {
        "methods": [ "GET" ],
        "route": "/swagger.{extension}"
      },
      "backendUri": "%OpenApi__BackendProxyUrl%/api/swagger.{extension}"
    }
  }
}
```
local.settings.json
```json
"OpenApi__BackendProxyUrl": "http://localhost:7072",
"AZURE_FUNCTION_PROXY_DISABLE_LOCAL_CALL": "true",
```
project.csproj
```xml
<ItemGroup>
    <None Update="proxies.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
</ItemGroup>
```
I tried to set the `CopyToOutputDirectory` to both Always and PreserveNewest. This did not change its behaviour.

**Comment by ClumsyPenguin** [comment]
well i guess this explains the issue ? [azure-functions-core-tools #2727](https://github.com/Azure/azure-functions-core-tools/issues/2727)

**Comment by justinyoo** [comment]
As @ClumsyPenguin provided the link, from the v4 runtime, the proxies.json feature is no longer supported. Instead Azure API Management Consumption Tier is recommended for that purpose.

**Comment by ClumsyPenguin** [comment]
What about local development?
