### ISSUE TITLE
Feature request: Add support for manipulating operations/schemas generation

### ISSUE THREAD

**Issue by alefranz** [Azure/azure-functions-openapi-extension#376]
**Describe the issue**
It would be nice to allow to implement custom logic to manipulate the generation of operations and schemas, similarly to what Swashbuckle provides: [Extend Generator with Operation, Schema & Document Filters](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#extend-generator-with-operation-schema--document-filters)

**Additional context**
One example scenario when this feature would be useful, is to extend the schema when not using DataAnnotations but a different form of validation (e.g. the popular FluentValidation)

**Comment by stephanruhland** [comment]
Support for _IDocumentFilter_ appears to be implemented: :+1:
https://github.com/Azure/azure-functions-openapi-extension/commit/3c9a76187296024936327e3563db622de09090f5

We also need _ISchemaFilter_ and _IOperationFilter_ support to switch to this great package.

**Comment by justinyoo** [comment]
@alefranz Thanks for the issue! As @stephanruhland mentioned, IDocumentFilter has been implemented.

Would you please create two separate issues for ISchemaFilter and IOperationFilter respectively so that I can have better tracking?

I'll close this issue for now.
