### ISSUE TITLE
Bug: When having 2 classes with the same name (in different namespaces), the Swagger UI do only show one of the classes

### ISSUE THREAD

**Issue by IcemanCoolFinger** [Azure/azure-functions-openapi-extension#379]
When using 2 classes with the same name, but in different namespaces, only one of the classes is defined in the Swagger UI and the json file. In the below sample, the class MessageBody exists in 2 different namespaces, but only one of them is shown in the Swagger UI and the json file.

The problem can be seen here: [https://bugsample-backstrom.azurewebsites.net/api/swagger/ui](https://bugsample-backstrom.azurewebsites.net/api/swagger/ui)

```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using System.Net;
using System.Threading.Tasks;

//First Dto class
namespace FirstSample
{
    public class MessageBody
    {
        public string EmployeeName { get; set; }
    }
    public class EmployeeMessageDto
    {
        public FirstSample.MessageBody MessageContent { get; set; }
    }
}

//Second Dto class
namespace SecondSample
{
    public class MessageBody
    {
        public string CompanyName { get; set; }
    }
    public class CustomerMessageDto
    {
        public SecondSample.MessageBody MessageContent { get; set; }
    }
}

namespace Functions
{
    public static class FunctionA
    {
        [FunctionName("FunctionA")]
        [OpenApiOperation(operationId: "FunctionA", tags: new[] { "name" })]
        [OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
        [OpenApiRequestBody("application/json", typeof(FirstSample.EmployeeMessageDto))]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.OK)]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult(string.Empty);
        }
    }

public static class FunctionB
    {
        [FunctionName("FunctionB")]
        [OpenApiOperation(operationId: "FunctionB", tags: new[] { "name" })]
        [OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
        [OpenApiRequestBody("application/json", typeof(SecondSample.CustomerMessageDto))]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.OK)]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult(string.Empty);
        }
    }
}
```

**Comment by MartinWickman** [comment]
I can confirm this as well. My assumption was that it got confused if using the same `route`, but it seems to be a more general problem. As it stands now, you cannot use the same exact class name more than once in your api:s. Workaround is to rename all classes and not rely on namespace.

**Comment by mwilde** [comment]
I had a similar issue. Two DTOs and both DTOs (different namespace) have a inner class with the same name. 
I found a fix where you should configure the SwaggerGen with
`builder.Services.AddSwaggerGen(options => options.CustomSchemaIds(i => i.FullName));`
but this results in an exception in the ui.

`Resolver error at components.schemas.....MyEvent.properties.entries.items.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/...MyEvent+InnerEntry does not exist in document`.

The problem ist that the FullName string contains a '+' as separator between main class and inner class.

To fix this kine of problem use:
`builder.Services.AddSwaggerGen(options => { options.CustomSchemaIds(i => i.FullName?.Replace("+", ".")); });` 

Now the generator and the ui is working with DTOs with inner classes with same names.

**Comment by corey-stidston** [comment]
@mwilde from what I can see AddSwaggerGen is not available in the package this issue relates to - Open Api extension for Azure Functions Microsoft.Azure.WebJobs.Extensions.OpenApi. Are you using Swashbuckle instead?

**Comment by tadlakha9** [comment]
any update on this ticket, when we are expecting it to be released.

Thank you

**Comment by justinyoo** [comment]
#610 has addressed this issue. The next `v2-preview` release will contain this fix.

**Comment by tadlakha9** [comment]
Any timeline when we have the new tag with this fix.

**Comment by Mivaweb** [comment]
Hi, came across this issue because we are also facing the same problem. Having a lot of DTO's in 2 namespaces with same namings. Installed the `2.0.0-preview2` but the `UseFullNamespace `is not available on the `IOpenApiConfigurationOptions`.

Any idea's when this can be made available?
