### ISSUE TITLE
OAuth redirect url is invalid

### ISSUE THREAD

**Issue by Derich367** [Azure/azure-functions-openapi-extension#384]
**Describe the issue**
The generated redirect url from swagger.js during OAuth2 workflow in swagger ui is invalid: "http://localhost:7071http://localhost:7071/api/oauth2-redirect.html"

**To Reproduce**
- Use Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.InProc example
- (not necessary but for better traceability): change "AuthorizationUrl" in PetStoreAuth.cs to any invalid url, so that you can see the full auth url without redirect
- Open http://localhost:7071/api/swagger/ui
- Start  oauth2 authorization
- Auth url contains "http://localhost:7071http://localhost:7071/api/oauth2-redirect.html" as redirect_uri parameter

**Expected behavior**
Auth url should contain "http://localhost:7071/api/oauth2-redirect.html" as redirect_uri parameter

**Environment (please complete the following information, if applicable):**
 - OS: Windows
 - Browser chrome
 - Version 98

**Comment by agravity-philipp** [comment]
I have a similar issue but for me the redirect URI seems to be: 'http://localhost:7071api/oauth2-redirect.html' and MSAL shows a AADSTS90102: 'redirect_uri' value must be a valid absolute URI. error message. I hope the hotfix #62 will bring the fix.

**Comment by usamaa9** [comment]
Need this fix, I'm seeing the same issue!

**Comment by ctraftoncodes** [comment]
I see that a fix has been made for this. Are there plans to bring this change in and release it?

**Comment by Hackmodford** [comment]
I can confirm that downgrading to 1.0.0 fixes the issue.

Here are my test results:

* 1.3.0 - broken
* 1.2.0 - broken
* 1.1.0 - broken
* 1.0.0 - works

**Comment by Alan-Hinton** [comment]
@justinyoo I see the release of this **bug** fix in version 1.0.4 is being held up by **enhancement** #369. I can work around this bug by manually editing the authentication url, but it is quite a pain.  Is there any chance of getting this bug fix released soon by bumping #369 to a later release.  I can't downgrade to an earlier version as others have suggested because I am using the excellent new Document Filters feature.
