### ISSUE TITLE
BAD IL Format when referencing a project that uses Microsoft.Azure.Cosmos nuget. 

### ISSUE THREAD

**Issue by marios-siati-kpmg** [Azure/azure-functions-openapi-extension#387]
**Describe the issue**

BAD IL Format when referencing a project that uses CosmosDb nuget. 

**To Reproduce**
1. Created an Out of Process as described in the sample projects. (https://github.com/Azure/azure-functions-openapi-extension/tree/4ab23d7e144370f9f2d7eb9d7e2b2daea1878a2d/samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc)
2. Reference another project that references CosmosDB library (Microsoft.Azure.Cosmos v3.25.0)
3. Run the project 
4. See error: 
`Bad IL format. The format of the file '.../bin/Debug/net6.0/Microsoft.Azure.Cosmos.ServiceInterop.dll' is invalid.`

**Expected behavior**
Swagger UI run without errors.

**Screenshots**
<img width="841" alt="image" src="https://user-images.githubusercontent.com/85685549/157081670-e9d826d0-4939-4424-9441-c2918a74326a.png">

**Environment (please complete the following information, if applicable):**
 - OS: MacOs

**Comment by willyt150** [comment]
Running into similar issue on Windows and when deployed up into azure linux consumption plan.

Issue shows up in version 1.2.0, 1.0.0 and 1.1.0 both do not have the issue.

Error in my case is: `Bad IL format. The format of the file '...\bin\Debug\net6.0\Cosmos.CRTCompat.dll' is invalid.`

**Comment by johnpeeke** [comment]
Same issue as @willyt150. Except I am deploying to a azure windows consumption plan. Using 1.1.0 alleviates the issue.

**Comment by andreasfrey** [comment]
Same issue here.

**Comment by justinyoo** [comment]
@marios-siati-kpmg Thanks for the issue! Let me repro this error on my end and get back to you.

**Comment by ihordyrman** [comment]
@justinyoo Could you please provide an approximate estimate of when this bug fix will be released?

**Comment by justinyoo** [comment]
This has been released to [v1.3.0](https://github.com/Azure/azure-functions-openapi-extension/releases/tag/v1.3.0). Thanks for waiting!
