### ISSUE TITLE
Cannot Override ForceHttps/ForceHttp

### ISSUE THREAD

**Issue by ctraftoncodes** [Azure/azure-functions-openapi-extension#391]
**Describe the issue**
The documentation for OpenApiOptions states that consumers may override this option when inheriting from `DefaultOpenApiConfigurationOptions`. However, these properties are not marked virtual and therefore cannot be overridden.

[Default OpenAPI Configuration](https://github.com/Azure/azure-functions-openapi-extension/blob/11d8d1a4a3e80a424db3484c69682f75d8d8d786/docs/openapi-core.md#inheriting-defaultopenapiconfigurationoptions)

**To Reproduce**
1. Create a class that overrides the `DefaultOpenApiConfigurationOptions` and attempt to override `ForceHttps` or `ForceHttp`.
![image](https://user-images.githubusercontent.com/75496244/159040778-bd337e79-5cae-40b8-808d-5ceb14f81a40.png)

**Expected behavior**
I am not sure what the expectation is. The documentation shows these values being overrideable but they are not marked virtual. Can you please help me to understand why these are not marked virtual if this is intentional?

If not, could they be made virtual?

**Comment by justinyoo** [comment]
@ctraftoncodes Thanks for the issue! It should have been marked as `virtual`. Would you please create a PR for it?

**Comment by justinyoo** [comment]
The initial intention was to use the environment variables.

https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md#force-http-or-https-for-swagger-ui
