### ISSUE TITLE
Microsoft.Graph `GraphServiceClient` initialisation results in No operations defined in spec!

### ISSUE THREAD

**Issue by KholofeloMoyaba** [Azure/azure-functions-openapi-extension#394]
**Describe the issue**
Initialising Microsoft.Graph `GraphServiceClient` anywhere in a function app that uses OpenAPI results in No operations defined in spec!

**To Reproduce**
1. Create a new Function App v4 .net 6, with an HttpTrigger with OpenAPI extension
2. Install Microsoft.Graph v4.21.0 (You may also need Azure.Identity v1.5.0 if you plan to make a working example)
3. Start function app
4. Notice that the swagger UI and swagger JSON has no operations

**Expected behavior**
Operations should be listed as per normal

Example code:
```
ClientSecretCredential credential = new ClientSecretCredential(
                    tenantId,
                    clientId,
                    clientSecret,
                    new TokenCredentialOptions
                    {
                        AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
                    });
            string[] scopes = new[] { "https://graph.microsoft.com/.default" };

            graphClient = new GraphServiceClient(credential, scopes);
```

commenting out the final line solves the issue. It seems that somehow GraphServiceClient's constructor disturbs something on the OpenAPI side.

**Environment (please complete the following information, if applicable):**
 - Version: Microsoft.Azure.WebJobs.Extensions.OpenApi 1.2.0

**Additional context**
I am writing a function app to manage B2C users via the GraphAPI. I'm using OpenAPI to maintain and share the documentation.

**Comment by KholofeloMoyaba** [comment]
@justinyoo that's not the issue. Sorry maybe I wasn't clear.

I'm not trying to expose Graph API directly via the extension. I have a function app that has a dependency on Graph API. For some reason the very fact that I'm using Graph API in my function app makes the OpenAPI extension not work any more (for any endpoint even ones that have nothing to do with Graph API).

Please can we reopen the issue @justinyoo ?

**Comment by KholofeloMoyaba** [comment]
> @KholofeloMoyaba Thanks for the issue!
> 
> If you want to expose Microsoft Graph API through your Azure Functions app, you should do it by yourself. This extension doesn't automatically expose Graph API endpoints.

See comment above. Please let me know if there is any extra info I can supply. But I would really appreciate some direction on this issue, so if we can please re-open it.

**Comment by justinyoo** [comment]
It would be also good to know whether you're running in-proc app or out-of-proc app

**Comment by KholofeloMoyaba** [comment]
> Oh, then did you get any error screen or so that you can put here? I'm not sure what isssue you're currently facing.

We are running in-proc

Basically the issue is that the swagger definition is empty as soon as we have Graph nuget in our code and we are initialising it anywhere. as you can see below:
<img width="1511" alt="Screenshot 2022-03-23 at 17 13 19" src="https://user-images.githubusercontent.com/4819593/159732366-dce7acee-1b97-4a28-801d-8cb31fcac7f9.png">

But commenting out usage of GraphAPI then the definitions show.

**Comment by KholofeloMoyaba** [comment]
@justinyoo the new version works! 🎉

Thank you very much. I'm happy for the issue to be closed.

Out of interest what was the underlying issue that was causing this? Is it somewhere on the 1.3.0 changelog?

**Comment by justinyoo** [comment]
Yes, there’s the change log in the `release-notes` directory.

**Comment by KholofeloMoyaba** [comment]
> Yes, there’s the change log in the `release-notes` directory.

None of the PR reference this issue. So I can't really tell what this issue was. But it's really out of interest now, I'll dig around the PRs and try and see. Thank you once again for the help.

**Comment by justinyoo** [comment]
It was #381 and #387
