### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.OpenApi  Function key box for authorization code is not displayed in the swagger interface

### ISSUE THREAD

**Issue by amalea** [Azure/azure-functions-openapi-extension#398]
Hello,

This request is linked to this [issue](https://github.com/Azure/azure-functions-openapi-extension/issues/353).

I'm using the OpenApi Extensions in a Azure Functions app, netcoreapp3.1.
I have replaced the old lib (Aliencube.AzureFunctions.Extensions.OpenApi) with the new one (Microsoft.Azure.WebJobs.Extensions.OpenApi), but I have an issue now with the authorization.
My HttpTrigger has AuthorizationLevel.Function.
Using the old lib, I had a 'function key' box where I could enter the function key (a function might have more keys).
![image](https://user-images.githubusercontent.com/14162970/159665865-1f891740-4098-42f9-afc9-38ad6f11861a.png)

With the new lib, I can use [OpenApiSecurity("function key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)], but how to use this with multiple function keys? Is there any way of doing this without hardcoding the function key?

Thank you and Best regards,

**Comment by tommck** [comment]
@justinyoo  - I wish you would reconsider. Not having the code in the Swagger UI makes the Swagger UI non-functional.  I can't use the UI in order to test the APIs anymore.  What's the point in the UI if you can't use it?  Otherwise, it's just a pretty way to display the JSON content.
