### ISSUE TITLE
Type of TimeSpan incorrectly inferred as complex object instead of string

### ISSUE THREAD

**Issue by basilfx** [Azure/azure-functions-openapi-extension#401]
**Describe the issue**
The type that is inferred for a `TimeSpan` is a complex object. Instead, I would expect a `string` (something like `1.00:00:00`).

A simple `HttpTrigger` that returns an `OkObjectResult` serializes a `TimeSpan` to a string, whereas the extension resolves a complex object for its schema definition. If I am correct, the OkObjectResult uses the Newtonsoft.Json serializer.

I tried to 'override' it using a `JsonConverter` attribute, but that does not work. Neither does adding `[DataType(DataType.Duration)]`.

**To Reproduce**
See this demonstration project: https://github.com/basilfx/azure-functions-openapi-function-timespan

**Expected behavior**
`TimeSpan` schema type is inferred as a `string`.

**Screenshots**
Note how the result is different from the example schema.

<img width="1444" alt="Schermafbeelding 2022-03-23 om 22 28 54" src="https://user-images.githubusercontent.com/815976/159798935-7ff227c4-8697-4a59-8559-4f5825e827da.png">

<img width="378" alt="Schermafbeelding 2022-03-23 om 22 46 27" src="https://user-images.githubusercontent.com/815976/159801285-f173e9f3-edf1-4ede-99c2-d698f14bf8b8.png">

**Environment (please complete the following information, if applicable):**
- OS: macOS
- Azure Functions v4
- .NET SDK 6.0.102
- OpenAPI Extension 1.2.0

**Comment by justinyoo** [comment]
@basilfx Thanks for the issue! Did you mean the TimeSpan instance should look like this?

https://dotnetfiddle.net/tyLTMW

**Comment by basilfx** [comment]
Yes, that's what I would expect, and that is how Newtonsoft.Json (used by AF for serializing an [IActionResult](https://github.com/basilfx/azure-functions-openapi-function-timespan/blob/master/MyHttpTrigger.cs#L22)) serializes a TimeSpan by default.

**Comment by snerte** [comment]
I am also running into this issue. As I am generating a client, the deserialization will fail.

**Comment by basilfx** [comment]
@justinyoo Any update on this issue? Anything I can do to help?

**Comment by sinantutan** [comment]
Did you by chance find a workaround/fix?
