### ISSUE TITLE
Feature request: Option to disable syntax highlighting

### ISSUE THREAD

**Issue by Skovvart** [Azure/azure-functions-openapi-extension#405]
**Describe the issue**
Swagger UI is notoriously slow at rendering large response bodies. 
This was supposedly made especially bad in SwaggerUI 3.x after syntax highlighting was introduced.

Luckily, it seems there is an option to [disable syntax highlighting](https://github.com/swagger-api/swagger-ui/issues/3832#issuecomment-698531637)

```javascript
SwaggerUI({
        syntaxHighlight: {
          activated: false,
          theme: "agate"
        },
        //url: path,
        ....
      });
```

Can this extension allow us to disable syntax-highlighting in Swagger UI?
A good candidate for configuring this would be `DefaultOpenApiConfigurationOptions` where the current behavior can be kept as the default.

**Comment by justinyoo** [comment]
@Skovvart Thanks for the issue! You can add a custom JS file for it - [doc](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#swagger-ui-customisation). Have you tried it?

**Comment by Skovvart** [comment]
@justinyoo I have not, I was unaware that was an option.

From what I can see, I am not sure it will do the trick, as it seems like the option needs to be passed in in the SwaggerUI instantion call (https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/dist/index.html#L44-L56)

**Comment by Skovvart** [comment]
More savvy frontend colleagues of mine proposed the following, which seems to work (though it feels pretty hackish)

`dist\custom.js`:
```javascript
// Use addEventListener instead of window.onload as that will be overwritten
window.addEventListener("load", function () {
    // Use setTimeout to wait until window.onload has executed
    setTimeout(function () {
        window.ui.getConfigs().syntaxHighlight.activated = false;
    }, 0);
});
```
