### ISSUE TITLE
default "Code" query string on all functions

### ISSUE THREAD

**Issue by lcordidrocl** [Azure/azure-functions-openapi-extension#41]
Hey, I get this parameter on requests of all my functions, and I don't know where it is coming from, since I am not specifying it with the data annotations:
"parameters": [
  {
      "in": "query",
      "name": "code",
      "type": "string"
  }]
  
  I am using default functionality to retrieve the swagger.json. With this I mean I haven't changed any setting after I installed the nuget package and added some data annotations to my functions.

**Comment by justinyoo** [comment]
@lcordidrocl Which version of the extension are you using?

**Comment by justinyoo** [comment]
I used the latest version of the [NuGet package](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/), `v0.3.2-preview`. I don't see your issue.

**Comment by lcordidrocl** [comment]
mm weird, I am using the same as you. I might have a wrong configuration somewhere on my function app then.
Thanks for taking the time to research, this points me that there is something wrong on my code. 
Thanks!
