### ISSUE TITLE
Feature request: Add ability to aggregate swagger docs using yet-to-be-released CLI tool

### ISSUE THREAD

**Issue by brennfoster** [Azure/azure-functions-openapi-extension#417]
Function apps are a great way to implement a microservice architecture. When creating serverless APIs, it would be nice to combine the outputted swagger docs into one document. I know there is a plan to release a CLI tool for the OpenAPI extension. Having the ability to aggregate the swagger docs would be very beneficial.

**Comment by justinyoo** [comment]
@brennfoster Thanks for the issue! Unfortunately, it's out-of-scope that this extension supports.
