### ISSUE TITLE
Using JWT bearer token configuration results in "Unknown security definition type" 

### ISSUE THREAD

**Issue by DeVliegendeBeer** [Azure/azure-functions-openapi-extension#425]
Using version 1.3.0
.NET 6
Functions isolated V4

With the following configuration of OpenApi on our Function HTTP trigger endpoint:
```        [Function(nameof(GetXXX))]
        [OpenApiOperation(operationId: nameof(GetXXX), tags: new[] { "XXX" })]
        [OpenApiSecurity("OAuth token", SecuritySchemeType.Http, Scheme = OpenApiSecuritySchemeType.Bearer, BearerFormat = "token", In = OpenApiSecurityLocationType.Header)]
        [OpenApiParameter("param1", In = ParameterLocation.Path, Type = typeof(int), Required = true)]
        [OpenApiParameter("param2", In = ParameterLocation.Query, Type = typeof(List<string>), Required = false)]
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(IList<XXXModel>))]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.Unauthorized)]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.InternalServerError)]
        public async Task<HttpResponseData> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "xxx/{abc}/yyy")] HttpRequestData request, int abc)
        {
```

we always get the message "Unknown security definition type"
![image](https://user-images.githubusercontent.com/33619496/165091655-21152681-0fec-4624-b0dd-d6410576b6af.png)

What are we doing wrong in the configuration for OpenApiSecurity?

**Comment by kaka2k** [comment]
I am having the same issue.  Configuration is 
`[OpenApiSecurity("Bearer", SecuritySchemeType.Http, Name = "authorization", Scheme = OpenApiSecuritySchemeType.Bearer, In = OpenApiSecurityLocationType.Header, BearerFormat = "JWT" )]`

**Comment by DeVliegendeBeer** [comment]
@kaka2k I found the solution in this earlier issue https://github.com/Azure/azure-functions-openapi-extension/issues/107#issuecomment-830672190

It is now working for me after I implemented IOpenApiConfigurationOptions

**Comment by computasjorn** [comment]
Bump. I have the same issue.
