### ISSUE TITLE
Add support for multiple examples

### ISSUE THREAD

**Issue by tofi92** [Azure/azure-functions-openapi-extension#436]
**Describe the issue**
I have difficulties generating multiple examples. Maybe I'm doing something wrong, but I cannot find further documentation on this.

**To Reproduce**
I'm using the following code to generate my examples. The first example works, but the second example is not generated:

    public class AbstractClassExample : OpenApiExample<AbstractClass>
    {
        public AbstractClassExample ()
        {
        }

        public override IOpenApiExample<AbstractClass> Build(NamingStrategy namingStrategy = null)
        {
            Examples.Add(OpenApiExampleResolver.Resolve("Example1", new ConcreteClass1()
            {
                SomeProperty = "SomeValue",
            }, namingStrategy));

            Examples.Add(OpenApiExampleResolver.Resolve("Example2", new ConcreteClass2()
            {
                SomeOtherProperty = "SomeOtherValue",
            }, namingStrategy));

            return this;
        }
    }

    [OpenApiExample(typeof(AbstractClassExample))]
    public abstract class AbstractClass
    {
    }

    [OpenApiExample(typeof(AbstractClassExample))]
    public class ConcreteClass1: AbstractClass
    {
        public string SomeProperty { get; set; }
    }

    [OpenApiExample(typeof(AbstractClassExample))]
    public class ConcreteClass2: AbstractClass
    {
        public string SomeOtherProperty { get; set; }
    }

**Expected behavior**
Both examples are selectable in Swagger UI (described [here](https://swagger.io/docs/specification/adding-examples/))

**Screenshots**
Generated UI:
![image](https://user-images.githubusercontent.com/8749424/168040490-f4f6f1d4-a588-4e0c-b52b-cc3ee299b004.png)
![image](https://user-images.githubusercontent.com/8749424/168040520-d501a07e-2637-4ecc-9ce2-03f425bdac33.png)

Generated json:
`
  {
    "swagger": "2.0",
    "info": {
      "title": "OpenAPI Document on Azure Functions",
      "version": "1.0.0"
    },
    "host": "localhost:7071",
    "basePath": "/api",
    "schemes": [
      "http"
    ],
    "paths": {
      "/Function1": {
        "post": {
          "operationId": "Post",
          "consumes": [
            "application/json"
          ],
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "in": "body",
              "name": "body",
              "required": true,
              "schema": {
                "$ref": "#/definitions/abstractClass"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "The OK response",
              "schema": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "definitions": {
      "abstractClass": {
        "type": "object",
        "example": "{\"someProperty\":\"SomeValue\"}"
      }
    }
  }
`
**Additional context**
![image](https://user-images.githubusercontent.com/8749424/168039963-68cdee74-6821-4702-a8f4-27d153fffc3b.png)

**Comment by tofi92** [comment]
Fixed by RTFM: inheriting from ```DefaultOpenApiConfigurationOptions``` and setting ```public override OpenApiVersionType OpenApiVersion { get; set; } = OpenApiVersionType.V3;```

**Comment by ClassyCircuit** [comment]
For anyone using the latest .NET 7 (isolation), here is what you need to register in program.cs:

```
		var host = new HostBuilder()
		.ConfigureFunctionsWorkerDefaults(worker => worker.UseNewtonsoftJson())
		.ConfigureServices((context, services) =>
		{
			services.AddSingleton<IOpenApiHttpTriggerContext, OpenApiHttpTriggerContext>();
			services.AddSingleton<IOpenApiTriggerFunction, OpenApiTriggerFunction>();

			services.Configure<OpenApiConfigurationOptions>(options =>
			{
				options.Info = new OpenApiInfo
				{
					Title = "Your API Title",
					Version = "v1",
					Description = "Your API Description"
					//... other properties
				};

				options.OpenApiVersion = OpenApiVersionType.V3;
				//... additional configurations as needed
			});
		})
		.Build();
```
