### ISSUE TITLE
Better support for dependency injection

### ISSUE THREAD

**Issue by ramesh-cs** [Azure/azure-functions-openapi-extension#458]
**Describe the issue**
Currently constructor injection is not supported for many classes, I have come across DefaultOpenApiConfigurationOptions which complains about missing parameter less constructor `No parameterless constructor defined` when the deriving class uses  constructor with parameter. I have also noticed the same is reported for a different class [here ](https://github.com/Azure/azure-functions-openapi-extension/issues/168). 

**Screenshots**
![image](https://user-images.githubusercontent.com/4073740/176627853-5785897f-5512-42b1-aac3-80e75cfb3da0.png)

**Environment (please complete the following information, if applicable):**
 - Version [1.3.0]

**Comment by jackbatzner** [comment]
This has been covered in the following PRs: #435 , #430 . Still awaiting review and comments from the repo owners
