### ISSUE TITLE
Add support for free-form query parameters

### ISSUE THREAD

**Issue by charch1219** [Azure/azure-functions-openapi-extension#465]
Add support for free-form query parameters as described [here](https://stackoverflow.com/questions/49582559/how-to-document-dynamic-query-parameter-names-in-openapi-swagger).

**Comment by justinyoo** [comment]
@charch1219 As this extension should both OpenAPI v2 (Swagger) and v3, I don't think I can add this dynamic query parameters feature as described in the first answer.
