### ISSUE TITLE
Getting CORS Issue while using OAuth 2 Client Credentials flow

### ISSUE THREAD

**Issue by vinodrpatgithub** [Azure/azure-functions-openapi-extension#471]
Hi @justinyoo,
I am facing below CORS Issue while using OAuth 2 Client Credentials flow.

> Access to fetch at 'https://login.microsoftonline.com/MyTenantId/oauth2/v2.0/token)' from origin 'http://localhost:7057' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

If I disable Chrome  browser security as below it works.

> "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --disable-gpu --user-data-dir=C:/Users/[My user name]/AppData/"

 I am describing  OAuth 2 Client Credentials flow on my API with OpenApiSecurity attribute with the Flows property pointing to my (client credentials) configuration:

     `[OpenApiSecurity(ClientCredAuthFlow.SchemeName, SecuritySchemeType.OAuth2, Flows = typeof(ClientCredAuthFlow))]` 

My Client credentials configuration is as below

    public class ClientCredAuthFlow : OpenApiOAuthSecurityFlows
    {
        private string _authTokenRefreshUrl = Environment.GetEnvironmentVariable("AuthTokenRefreshUrl");
        private string _tenantId = Environment.GetEnvironmentVariable("TenantId");
        private string _clientId = Environment.GetEnvironmentVariable("ClientId");
        public const string SchemeName = "ClientCredAuthFlow";

        public ClientCredAuthFlow()
        {
            var scope = string.Concat("api://", _clientId, "/.default");

            this.ClientCredentials = new OpenApiOAuthFlow()
            {
                Scopes = { { scope, "Default scope defined in the app" } },
                TokenUrl = new Uri(string.Format(_authTokenRefreshUrl, _tenantId))
            };
        }
    }
   

How I can deal to this CORS issue.

I tried allowing CORS using local.settings.json as below

`{
  "IsEncrypted": false,
  "Values": {

  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*"
  }
}`

But still getting same error.

**Comment by justinyoo** [comment]
@vinodrpatgithub Thanks for reaching out! Assuming that you're using Azure AD's OAuth2 client credential flow.

When I look at your code snippet, I see your scope setting is slightly different:

```csharp
var scope = string.Concat("api://", _clientId, "/.default");
```

According to the [Microsoft Graph document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), it should be `https://graph.microsoft.com/.default`.

Have you tried that?

**Comment by vinodrpatgithub** [comment]
Thanks @justinyoo for your response.
I tried using 'https://graph.microsoft.com/.default' but I am not able to get token with it. [Microsoft Graph document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), mentioned applicationID Uri with .default suffix as well as below.

The value passed for the scope parameter **in this request should be the resource identifier (application ID URI) of the resource you want,** affixed with the .default suffix. For the Microsoft Graph example, the value is https://graph.microsoft.com/.default.

Also my _authTokenRefreshUrl  is 'https://login.microsoftonline.com/{0}/oauth2/v2.0/token'

**Comment by justinyoo** [comment]
Let me try on my end and get back to you.

**Comment by vinodrpatgithub** [comment]
Hi @justinyoo , I have added sample code for your reference here - https://github.com/vinodrpatgithub/AzureAd-oAuth-ClientCred-OpenApi . Few settings needs to be updated in ''appsettings.json" and "local.settings.json" from Azure Ad app.
Please let me know if you need any additional details.

**Comment by mikanygTC** [comment]
I have the same issue (and code setup) for both Client Credentials, and I see similiar problems for the Authorization Code flow that the CORS policy is blocking communication between the Swagger UI page and the AAD token endpoints.

Happens both when running locally and when hosted in Azure functions app.

**Comment by justinyoo** [comment]
Please make sure that you can't use the client credential auth flow on SPA. [The client credentials workflow document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) describes that it needs a server or daemon, instead of SPA (Swagger UI in our case).

We can't use the authorisation code auth flow either due to the lack of support of PKCE certificate. We will start supporting this feature when the OpenAPI spec v3.1.0 is supported.

**Comment by vinodrpatgithub** [comment]
Thanks @justinyoo for the clarification
