### ISSUE TITLE
OpenApi - Functions v4 - Net 6 - Endpoints are not generated

### ISSUE THREAD

**Issue by drma-dev** [Azure/azure-functions-openapi-extension#472]
Two points to raise:

1 - the template is being generated wrong. does not come with the components referencing correctly. and even after I fixed it, it doesn't open the swagger, nor does it create the endpoints.

2 - I tried several approaches, but none could make it work. several examples point to old versions, where there was a startup that doesn't even exist in the last version anymore. I also tried to create the classes that inherit from DefaultOpenApiConfigurationOptions and IOpenApiConfigurationOptions, but it didn't help.

**Comment by enzosambucetti** [comment]
You can add the startup file you need. Search how, but it is possible.

**Comment by drma-dev** [comment]
@enzosambucetti 
my project has startup. but theoretically in version .net core 6 + azure function 4 doesn't need that. so I don't know what's missing.

**Comment by enzosambucetti** [comment]
Meaby you missed the Decorations tags in each functions. Like this:

[OpenApiOperation("test", "test", Description = "test", Visibility = OpenApiVisibilityType.Important)]
[OpenApiRequestBody("application/json", typeof(Object), Required = true, Description = "object")]
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(Result<bool>), Description = "Test")]
        [FunctionName(nameof(TestAsync))]
        public async Task<IActionResult> TestAsync(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "v1/test")] HttpRequest req)
        {
            return Ok();
        }

**Comment by drma-dev** [comment]
@enzosambucetti it has too. everything that should be done has been done.

**Comment by enzosambucetti** [comment]
And what is the problem specific, you enter to the Url to see the swagger UI and you don t see endpoints? If that the case, put here a image with the nugget package installed in your project with the versions.

**Comment by drma-dev** [comment]
![image](https://user-images.githubusercontent.com/12803050/186271158-689c13a3-38f0-4b99-a2b6-e6ee0715f97b.png)

I don't know what the problem is. I've tried all the solutions I found on the internet. it simply does not generate the endpoints here, so it is impossible to access.

**Comment by enzosambucetti** [comment]
But.u installed the nugget? Open nugget manager and send image

**Comment by drma-dev** [comment]
the template has been changed. now it's working. I will test tomorrow in my project.

**Comment by enzosambucetti** [comment]
Can you give me the links to the templates?

**Comment by drma-dev** [comment]
![image](https://user-images.githubusercontent.com/12803050/186279447-aeeebfa5-31a2-44c0-a0c1-d082823ba9e8.png)

**Comment by drma-dev** [comment]
`Microsoft.Azure.WebJobs.Extensions.OpenApi`

It was the extension that works. I just don't know what the difference is.

@enzosambucetti

**Comment by Charugatra** [comment]
Adding Nuget Package Microsoft.Azure.Functions.**Worker**.Extensions.OpenApi resolved this issue for me

**Comment by drma-dev** [comment]
> Adding Nuget Package Microsoft.Azure.Functions.**Worker**.Extensions.OpenApi resolved this issue for me

I had already forgotten about this problem. I got it with this one. thanks.
