### ISSUE TITLE
Is there a way to remove "Try it out" functionality?

### ISSUE THREAD

**Issue by JoseGeorges8** [Azure/azure-functions-openapi-extension#475]
**Describe the issue**
I would like to remove being able to use the apis, and rather just display them as documentation.

I've seen other projects/packages do it with methods such as `SupportedSubmitMethods` ([This post talks about it](https://elanderson.net/2017/10/swagger-and-swashbuckle-disable-try-it-out/))

Is there currently a way of doing this with this package, or is there plans to add this in the future?

**Comment by justinyoo** [comment]
@JoseGeorges8 Thanks for the issue. We don't provide disabling the "Try it out" button out-of-the-box. But, you can do it by adding a custom JavaScript file or CSS file to hide/remove it.

**Comment by JoseGeorges8** [comment]
@justinyoo thanks for the reply! So I saw an issue that points at [this video](https://www.youtube.com/watch?v=hC44iF0luR0&t=1915s) on how to apply this custom css, but I was unlucky.

My project structure looks like this:

- src
    - *.csproj
    - /OpenAPI
        - /Configurations
            - OpenApiCustomUIOptions.cs
        - /Styles
            - styles.css
 

And here's how I've built the OpenApiCustomUIOptions.cs:

```

using System.Reflection;
using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Configurations;

namespace src.OpenAPI.Configurations;
public class OpenApiCustomUIOptions : DefaultOpenApiCustomUIOptions
{
    public OpenApiCustomUIOptions(Assembly assembly) : base(assembly)
    {
    }

    public override string CustomStylesheetPath {get;} = "OpenAPI.Styles.styles.css";

}

```

However the styling doesn't get applied. Am I missing anything?

I'm using OpenApi__Version : v3

Thanks in advanced!

**Comment by JoseGeorges8** [comment]
Update: I found we need to add the files as an embedded resource. Thanks!
