### ISSUE TITLE
GetSwaggerAuthKey should not return nullable string

### ISSUE THREAD

**Issue by michielpost** [Azure/azure-functions-openapi-extension#48]
I'm using the OpenApi Extensions in a Azure Functions app, netcoreapp3.1 with nullability enabled and nullability warnings are treated as errors.

My csproj contains this:

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp3.1</TargetFramework>
  <AzureFunctionsVersion>V3</AzureFunctionsVersion>
  <LangVersion>9.0</LangVersion>
  <Nullable>enable</Nullable>
  <WarningsAsErrors>nullable</WarningsAsErrors>
</PropertyGroup>
```

But when the `Microsoft.Azure.WebJobs.Extensions.OpenApi` (version: `0.4.0-preview`) NuGet package is included, it won't compile anymore. 
It's caused by the template file `OpenApiHttpTriggerContext.cs` that is included in the project. It contains a `GetSwaggerAuthKey` method, which returns a `string`.

```cs
public virtual string GetSwaggerAuthKey(string key = "OpenApi__ApiKey")
{
  var value = Environment.GetEnvironmentVariable(key);

  return value;
}
```

But `Environment.GetEnvironmentVariable(key)` returns a nullable string: `string?`
So now my compiler is unhappy and returns this error:
```
Error	CS8603	Possible null reference return.
microsoft.azure.webjobs.extensions.openapi\0.4.0-preview\contentFiles\any\netstandard2.0\OpenApi\OpenApiHttpTriggerContext.cs	121	Active
```

I submitted a fix in PR #49

**Comment by justinyoo** [comment]
@michielpost This has been released to [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.5.0-preview).
