### ISSUE TITLE
RenderSwaggerUI Missing From Functions When Deployed In Azure

### ISSUE THREAD

**Issue by bakes82** [Azure/azure-functions-openapi-extension#495]
When I deploy the FA to azure, the "render" endpoints arent shown in the list but they do respond if I goto them via the URL.

**Comment by justinyoo** [comment]
Hi, @bakes82 Thanks for the issue! If you run the Azure Functions app in-proc, it's the expected behaviour that you can't see those rendering endpoint on Azure Portal. However, it's working as expected.
