### ISSUE TITLE
When to expecte 1.0?

### ISSUE THREAD

**Issue by lecamarade** [Azure/azure-functions-openapi-extension#50]
Hi,

Could you please share the timeline for this project?
I'd love to start using it, would be very helpful to know when to expect a prod ready version.

**Comment by bradygaster** [comment]
We are hoping to release an initial version of this in Spring 2021. If you have started tinkering with it and trying things out we'd love your feedback so far.

**Comment by bradygaster** [comment]
Closing this issue as we answered it as best we can. :) Keep watching out, and keep issues coming if you notice anything wonky walking through the docs. I'm about to submit a small issue now. 👍
