### ISSUE TITLE
V4 proxie support is still not happening? 

### ISSUE THREAD

**Issue by MacMcDell** [Azure/azure-functions-openapi-extension#502]
**Describe the issue**
I have route endpoints that should be resolving to other endpoints. I reviewed the article by @JustinYoo but it seems this functionality is still not supported in V4. https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/shortening-swagger-ui-page-url.md Wondering if there is some other functionality they enabled to make this work? 
Proxie support seems all over the place when it comes to being supported or not supported. If Proxies are not supported, the proposed solution to use rewrite the swagger/ui endpoint will not work and the only solution is to use API Management or similar on the Azure portal? I should note that V3 proxies work absolutely fine for the proposed solution. V4 seems to be not working at all. 

**Environment (please complete the following information, if applicable):**
Ver 1.40
Azure V4 / dotnet 6 isolated.

**Additional context**

**Comment by justinyoo** [comment]
@MacMcDell The proxy feature has been removed from the v4 runtime. I know it will be back (it's in their backlog), but not sure exactly when it will be. In the meantime, you can use APIM (consumption tier) as an alternative.

**Comment by MacMcDell** [comment]
Yeah ok thanks @justinyoo . It sucks we can't test locally any of these. Also my understanding is even if we use APIM, they will resolve, but they won't show up in the swagger doc either unless we roll our own static document?

The only viable solution I have come up with right now is to create functions matching my current static swagger doc and make pointers to the original like so: 
![image (2)](https://user-images.githubusercontent.com/1512821/197550533-54df365f-c5fc-41bf-aa70-044f4ee7add5.png)
