### ISSUE TITLE
Integration with OpenAPI.NET.CSharpAnnotations

### ISSUE THREAD

**Issue by alvpickmans** [Azure/azure-functions-openapi-extension#51]
Hi! I'm just looking into different options to better document Azure Functions API projects and I think the project seems pretty useful.

Although the use of attributes to document seems to be working good, I was wondering if there is any plan (or has been considered) to integrate with https://github.com/microsoft/OpenAPI.NET.CSharpAnnotations to allow retrieving OpenAPI specs from a method's annotations.

It feels counter productive if one wants to document both the OpenAPI and the method to duplicate content on both annotations and attributes.

Just a thought anyway.

Cheers!

**Comment by justinyoo** [comment]
@alvpickmans Thanks for the suggestion! We haven't considered the XML document annotation way for Open API support yet. But that's good to know!

**Comment by markleavesley** [comment]
This is marked as resolved but trying it with 0.8.1 and it does not use the annotations. I'm now faced with duplicating 173 annotations and that's just for one service 😱
