### ISSUE TITLE
Support of multiple examples per request

### ISSUE THREAD

**Issue by HT-Xaris** [Azure/azure-functions-openapi-extension#516]
**Describe the issue**
Currently, only one example per request is possible, since only the first example is forwarded to the API document via the attribute check. It would be cool if multiple examples are supported.

**To Reproduce**
1. Creating an HttpTrigger endpoint as a POST with a request payload object. 
2. Attaching the "OpenApiExampleAttribute" to the Request Payload object. 
3. Creating the sample implementation via "OpenApiExample<T>" and passing multiple samples in the "Build" method. 
4. Only the first example is generated in the UI.

**Expected behavior**
The dropdown to select an example is visible and can be used to change the given example data.

**Environment (please complete the following information, if applicable):**
 - OS: Windows
 - Browser: Edge
 - Package-Version: 1.4.0

**Comment by marcinburak** [comment]
Hi, I'm pretty sure this feature is supported.
Here's a sample I used to generate multiple request body examples with dropdown in the Swagger UI:

```csharp
public sealed class Request
{
    public string Content { get; set; } = string.Empty;
}

public sealed class RequestExample : OpenApiExample<Request>
{
    public override IOpenApiExample<Request> Build(NamingStrategy namingStrategy = null)
    {
        var camelCaseNamingStrategy = new CamelCaseNamingStrategy();

        Examples.Add(OpenApiExampleResolver.Resolve("Sample 1", new Request { Content = "Content 1" }, camelCaseNamingStrategy));
        Examples.Add(OpenApiExampleResolver.Resolve("Sample 2", new Request { Content = "Content 2" }, camelCaseNamingStrategy));
        Examples.Add(OpenApiExampleResolver.Resolve("Sample 3", new Request { Content = "Content 3" }, camelCaseNamingStrategy));

        return this;
    }
}

public static class MultipleExamplesSample
{
    [FunctionName(nameof(MultipleExamplesSample))]
    [OpenApiOperation(operationId: "multiple-examples-sample")]
    [OpenApiRequestBody(contentType: "application/json", bodyType: typeof(Request), Example = typeof(RequestExample))]
    public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest httpRequest) => new NoContentResult();
}
```
Mentioned sample results in the example dropdown:
![image](https://user-images.githubusercontent.com/29354406/214920836-866fe69f-ad0e-40a1-82aa-3393384863a3.png)

**Comment by justinyoo** [comment]
As @marcinburak mentioned, it's supported. Please take a look at [this document](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#openapiexampleattribute). You can add as many examples as you want.
