### ISSUE TITLE
How to get "AllOf" in the swagger definition?

### ISSUE THREAD

**Issue by a123456789012345** [Azure/azure-functions-openapi-extension#520]
I am using this library and I am getting this in the swagger

                    "data": {
                        "$ref": "#/components/schemas/createTransferResponseModel"
                    },

Is there a way or an annotation so that the resulting swagger will look like this:

          "data": {
            "allOf": [
              {
                "$ref": "#/components/schemas/createTransferResponseModel"
              }
            ],
            "nullable": true
          },

Note: for reasoning why I want the "AllOf" - this is due to the code-generated by NSwag, where without the nullable=true, then NSwag always expect it to be not-nullable, but there are scenarios where it can be null

**Comment by justinyoo** [comment]
@a123456789012345 Thanks for the issue! This extension currently doesn't support `allOf`, `anyOf` or `oneOf` yet.
