### ISSUE TITLE
<!-- XML example cannot be generated; root element name is undefined -->

### ISSUE THREAD

**Issue by insycaOps** [Azure/azure-functions-openapi-extension#535]
**Describe the issue**
Can't figure out how to get XML examples shown in swagger ui. 

Here is my code for the Sample

      public class RequestObjectExample : OpenApiExample<object>
	      {
		      public override IOpenApiExample<object> Build(NamingStrategy namingStrategy = null)
		      {
			      this.Examples.Add(
				       OpenApiExampleResolver.Resolve(
					       "Sample Data",
					       new { root = new { test = "asdasddasds" } }
				       ));
			      return this;
		      }
	      }

And here the attributes on the Azure Function

		[OpenApiOperation(operationId: $"{Label.Arda}_{Label.request}", tags: new[] { "SAMPLE" }, Summary = ardaLabel.functionSummary, Description = ardaLabel.functionDescription1 + ardaLabel.functionDescription2, Visibility = OpenApiVisibilityType.Important)]
		[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
		[OpenApiRequestBody(contentType: "application/json; charset=utf-8", bodyType: typeof(object), Example = typeof(RequestObjectExample), Description = ardaLabel.requestBodyDescription, Required = true)]
		[OpenApiRequestBody(contentType: "application/xml; charset=utf-8", bodyType: typeof(object), Example = typeof(RequestObjectExample), Description = ardaLabel.requestBodyDescription, Required = true)]
		[OpenApiRequestBody(contentType: "application/octet-stream", bodyType: typeof(byte[]), Description = ardaLabel.requestBodyDescription, Required = true)]
		[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain; charset=utf-8", bodyType: typeof(string), Example = typeof(ResponseServicebusExample), Summary = ardaLabel.responseSummary, Description = ardaLabel.responseDescription)]
		[OpenApiResponseWithoutBody(statusCode: HttpStatusCode.Unauthorized, Summary = ardaLabel.responseSummary401, Description = ardaLabel.responseDescription401)]
		[FunctionName($"{Label.Arda}_{Label.request}")]
		public async Task<IActionResult> Request(
			[HttpTrigger(AuthorizationLevel.Function, "post", "get", Route = "ada")] HttpRequest req,
			ILogger log,

**Expected behavior**
XML example shown in swagger ui

**Screenshots**
Output Xml
![image](https://user-images.githubusercontent.com/48807799/211347250-447b352e-2169-46a6-b501-fb131de1e254.png)
Output Json
![image](https://user-images.githubusercontent.com/48807799/211347332-7328460d-6993-4795-8be2-945c5005dd92.png)

**Environment (please complete the following information, if applicable):**
 - Azure Function V4, 
 - Net 6.0
 - Edge Browser/Windows 11

**Additional context**
---
Any Hint?

Thank you,
Iwe

**Comment by marcinburak** [comment]
Hey, I'm not a XML expert but I did some testing and perhaps my findings could help you out.
1. I suspect that specifying `bodyType: typeof(object)` prevents correct Open API definition generation - use a strongly typed class if you can to prevent document generation issues
2. You're using `OpenApiExampleResolver.Resolve()` method to generate your XML example but I did some debugging and the code execution ends up here: 
```csharp
 case TypeCode.Object:
    openApiExampleValue = new OpenApiString(JsonConvert.SerializeObject(instance, settings));
    break;
```
 which obviously generates the example as JSON and not XML.

Here is a sample code I used to get it to work:
```csharp
public static class XmlExample
{
    public class RequestObject
    {
        public RootElement Root { get; set; } = new();

        public class RootElement
        {
            public string Test { get; set; } = "test";
        }
    }

    public class RequestObjectJsonExample : OpenApiExample<RequestObject>
    {
        public override IOpenApiExample<RequestObject> Build(NamingStrategy namingStrategy = null!)
        {
            this.Examples.Add(OpenApiExampleResolver.Resolve("Sample Data", new RequestObject { Root = new() }, new CamelCaseNamingStrategy()));
            return this;
        }
    }

    public class RequestObjectXmlExample : OpenApiExample<RequestObject>
    {
        private static string ToXmlString<T>(T data)
        {
            var xmlSerializer = new XmlSerializer(typeof(T));

            using var stringWriter = new StringWriter();
            using var xmlTextWriter = new XmlTextWriter(stringWriter) { Formatting = Formatting.Indented };

            xmlSerializer.Serialize(xmlTextWriter, data);

            return stringWriter.ToString();
        }

        public override IOpenApiExample<RequestObject> Build(NamingStrategy namingStrategy = null)
        {
            this.Examples.Add("Sample Data", new OpenApiExample
            {
                Value = new OpenApiString(ToXmlString(new RequestObject()), isExplicit: false)
            });

            return this;
        }
    }

    [FunctionName(nameof(XmlExample))]
    [OpenApiOperation(operationId: "xml-example")]
    [OpenApiRequestBody(contentType: "application/json; charset=utf-8", bodyType: typeof(RequestObject), Example = typeof(RequestObjectJsonExample))]
    [OpenApiRequestBody(contentType: "application/xml; charset=utf-8", bodyType: typeof(RequestObject), Example = typeof(RequestObjectXmlExample))]
    public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequest httpRequest) => new NoContentResult();
}
```

This code results in correct Open API document:
```json
"/XmlExample": {
      "post": {
        "operationId": "xml-example",
        "requestBody": {
          "content": {
            "application/json; charset=utf-8": {
              "schema": {
                "$ref": "#/components/schemas/requestObject"
              },
              "examples": {
                "Sample Data": {
                  "value": "{\"root\":{\"test\":\"test\"}}"
                }
              }
            },
            "application/xml; charset=utf-8": {
              "schema": {
                "$ref": "#/components/schemas/requestObject"
              },
              "examples": {
                "Sample Data": {
                  "value": "<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<RequestObject xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Root>\r\n    <Test>test</Test>\r\n  </Root>\r\n</RequestObject>"
                }
              }
            }
          }
        },
        "responses": { }
      }
```

And here is the working UI:
![image](https://user-images.githubusercontent.com/29354406/214918323-108daf69-924c-4358-be67-29bdd2b7ea99.png)
![image](https://user-images.githubusercontent.com/29354406/214918360-0db9a9d0-11f6-462d-b72a-f7ae3c85c3be.png)

**Comment by justinyoo** [comment]
@insycaOps Thanks for the issue! Hope @marcinburak 's workaround would help sort out your issue.

Thanks @marcinburak for your workaround! We might need to add your workaround as a feature. Would you be willing to create a PR for it, please?
