### ISSUE TITLE
Can't get it to work using .net7 out-of-process model

### ISSUE THREAD

**Issue by ErikHen** [Azure/azure-functions-openapi-extension#549]
Using latest version of Visual Studio 2022

**To Reproduce**
1. Create new Azure function. Select .Net 7 Isolated
![image](https://user-images.githubusercontent.com/9220071/216824699-8e59668d-c505-40d2-b04b-c1dab58a0e9a.png)
2. Hit F5 and test that /api/Function1 works as expected.
3. Add nuget: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.OpenApi
4. Update Program.cs
replace: .ConfigureFunctionsWorkerDefaults()
with: .ConfigureFunctionsWorkerDefaults(worker => worker.UseNewtonsoftJson())
5. Hit F5. Goto  /api/Function1 or /api/swagger/ui. There is no respons, browser keep loading forever.

**Environment**
 - OS: Windows

**Comment by Jost3in** [comment]
Same problem. 
Using WSL and  .net6 or .net7 isolated

**Comment by ErikHen** [comment]
Thank you @Jost3in !
