### ISSUE TITLE
Is it possible to upgrade the swagger specification from v2 to v3.0.0?

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-functions-openapi-extension#56]
currently the swagger docs are generated using the 2.0 api:

```json
"swagger": "2.0",
```

but the latest is 3.0.3 https://swagger.io/specification/

**Comment by justinyoo** [comment]
@sonic1981 You can use /api/openapi/v3.json to get Open API v3 spec.

https://github.com/Azure/azure-functions-openapi-extension/blob/a06c271e70c276b12c243b41fac004fb01de4856/templates/OpenApiEndpoints/OpenApiHttpTrigger.cs#L80

**Comment by sonic1981** [comment]
Ah good one. Thanks

**Comment by Raysapps** [comment]
How can I override/ set the Open API version in the function app project to generate the swagger V 3.0?
To my understanding, "azure-functions-openapi-extension/templates/OpenApiEndpoints/OpenApiHttpTrigger.cs"  code is in the extension.dll and not sure how to reconfigure it in the function app.

**Comment by justinyoo** [comment]
@Raysapps Let's discuss it on a separate issue, #84
