### ISSUE TITLE
"offline" generation of OpenAPI definition for use in build pipeline

### ISSUE THREAD

**Issue by filcole** [Azure/azure-functions-openapi-extension#58]
When working with a solution containing a PowerPlatform custom connector that uses an OpenAPI definition generated from an Azure Function it would be good to be able to output the OpenAPI definition (v2 currently only for custom connectors) within a build pipeline.  

This would remove the manual step of having to update the custom connector YAML, then export the solution containing the custom connector.

**Comment by justinyoo** [comment]
@filcole Did you mean the CLI version of it? Could you please elaborate a bit more?

**Comment by filcole** [comment]
Hi @justinyoo, 

Yes something like the CLI version from the Aliencube repo - so that a build process can "compile" and generate an OpenAPI definition which can then be included in the "source" for a PowerPlatform custom connector.  Custom connectors in PowerPlatform solutions can be exploded into individual files using the solutionpackager.exe tool.  Each custom connector has it's own directory which contains five files:
* <connectorname>.xml   <- the metadata for the connector used by the solution
* <connectionname>_connectionparameters.xml  
* <connectionname>_iconblob.png  <- the custom connector icon
* <connectionname>**_openapidefinition**.json   <- this appears to be a OpenAPI v2 definition we can replace by the CLI generated version
* <connectionname>_policytemplate.json   <- policy template used when a connection is used/made.

At the moment the Azure Functions OpenAPI extension forces us to publish to Azure before being able to download an OpenAPI definition.  Ideally, this should be done at build time, especially when managed solutions in the power platform are used (as MS recommend these days).

**Comment by sonic1981** [comment]
Yes, I wanted to really publish my open api separate to my functions but I can't currently as the json is built on the fly. I'd prefer if the json could be built by my deployment pipeline and then deployed to a web app separate to my function apps. Not least of which because of security.

**Comment by svrooij** [comment]
This would serve multiple purposes:

1. Generating at build time (and serving a static json file) is probably faster then generating it at runtime every time `api/openapi/v2.json` is called.
2. If this file is available at build time we could use [NSwag](https://github.com/RicoSuter/NSwag) to generate strong typed clients (C# or TypeScript), which could then also be published some where.

The last use case for us it that we have this Azure Functions api and a accompaning Angular SPA. The services classes in this Angular SPA are strong typed based on the openapi specifications. So if we change something in the api, a single build (in debug mode) would be enough to also automatically update the services in the TypeScript application.

**Comment by justinyoo** [comment]
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/132

**Comment by justinyoo** [comment]
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/126

**Comment by sabryguen** [comment]
Hey @justinyoo, is there an ETA on this feature? I have similar demand for generating a swagger.json file as part of the build pipeline.

Can you think of any workarounds for the time being?

Thanks,

Sabry

**Comment by jeromekol** [comment]
> Hey @justinyoo, is there an ETA on this feature? I have similar demand for generating a swagger.json file as part of the build pipeline.
> 
> Can you think of any workarounds for the time being?
> 
> Thanks,
> 
> Sabry

Bit late, but I've been using the code that is in the CLI folder on this repo: https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI/Program.cs

Maybe that helps someone else.
