### ISSUE TITLE
Using nuget package in sample Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc fails

### ISSUE THREAD

**Issue by niklassaers** [Azure/azure-functions-openapi-extension#594]
Hi,
I followed the instructions in https://github.com/Azure/azure-functions-openapi-extension/blob/main/samples/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.FunctionApp.OutOfProc.csproj with commenting in line 13-15 and commenting out line 24-28. This failed to compile, with a "_The type or namespace name 'AutoFixture' could not be found"_.

Trying to fix that and the following missing "Microsoft.Azure.WebJobs.Extensions.OpenApi", I replaced line 14 with
```
<PackageReference Include="AutoFixture" Version="4.18.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
```

However, I now get a warning saying that the project has a strict requirement of Microsoft.CodeAnalysis.CSharp.Workspaces being version 3.3.1, but it resolves to 3.11.0.
I also get a number of compile errors because "using Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.Models;" does not exist.

Can you help me getting the out-of-process sample to compile and run (I'd like it see producin /api/swagger.json) via the nuget package?

I'm running dotnet 7.0.200 with the Azure Function tools version 4.0.5095 on an M1 based macOS Ventura (13.4.1) setup.

**Comment by justinyoo** [comment]
Thanks for the issue. It's now fixed.
