### ISSUE TITLE
Allow extensibility of swagger UI with custom stylesheets

### ISSUE THREAD

**Issue by ssa3512** [Azure/azure-functions-openapi-extension#60]
As a consumer of this package, I would like the ability to override some of the CSS contained in the `dist` folder with some of my own to be able to provide some custom branding on the swagger UI site.

It would be great to have some methods that can be overridden in [SwaggerUI](https://github.com/Azure/azure-functions-openapi-extension/blob/main/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/SwaggerUI.cs) to enable the inclusion of custom stylesheets to be included above the `[[SWAGGER_UI_CSS]]` placeholder in `index.html`.

**Comment by justinyoo** [comment]
@ssa3512 Thanks for suggestion! It surely will be supported.

**Comment by ssa3512** [comment]
@justinyoo is there any sort of specific release cadence for this project? Any thoughts on when this will get included in a nuget package?

**Comment by justinyoo** [comment]
@ssa3512 We don't have a regular cadence for the release in place yet. We're currently looking at a few bugs to be included in the next release, though.

**Comment by justinyoo** [comment]
@ssa3512 It's been released to [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.6.0-preview). Please have a look and let us know.
