### ISSUE TITLE
Swagger "try it out" with funcktion / host key 

### ISSUE THREAD

**Issue by canturan** [Azure/azure-functions-openapi-extension#63]
How can I use or extend the "try it out" functionality from swagger ui, if i I deployed the solution to Azure function, while using AuthorizationLevel.Function. "Try it out" does not respect the  OpenApi__ApiKey settings and sends the request without key, which causes 401 Unauthorized. 

Is there any way or attribute to configure it, that "try it out" sends the request with the function key or with the OpenApi__ApiKey from the settings.

**Comment by justinyoo** [comment]
@canturan Thanks for bringing up the issue.

The `OpenApi__ApiKey` is only used if you want to secure your Swagger UI and Open API document endpoints such as `/api/swagger/ui`, `/api/swagger.{extension}`, `/api/openapi/{version}.{extension}`.

If you want to authenticate your endpoints other than them, you should add the `OpenApiSecurityAttribute` decorator on each HTTP trigger, and authenticate the endpoints by yourself.

**Comment by JounouchiAng** [comment]
You can authenticate using HTTP Header by passing ' x-functions-key' with your function/master key.

**Comment by justinyoo** [comment]
@canturan I wonder whether it has answered your question. I'll close this ticket in a couple of days time.

**Comment by canturan** [comment]
@justinyoo @JounouchiAng Thank you! The OpenApiSecurityAttribute with "x-functions-key" works perfectly fine.
