### ISSUE TITLE
Setting the base url in isolated worker azure function

### ISSUE THREAD

**Issue by Glowiksi** [Azure/azure-functions-openapi-extension#639]
**Describe the issue**
Hello, 

I currently have an azure function isolated-worker running on my local machine and after setting up swagger it takes another port as the default one. Therefore it can not load the swagger.json nor call the api because of CORS and wrong setup. 

Setup:
MacBook Pro M2 or Windows 10 (Dell)
Jetbrains Rider
.NET 8
Microsoft.Azure.Functions.Worker.Extensions.OpenApi 1.5.1

**To Reproduce**
1. Start your app to port 7071 - which is needed in my case. 
2. Open the swagger ui
3. Get a big red banner with an error
4. See the base url on the top left has not changed

**Expected behavior**
I expect to set the baseurl in the IOpenApiConfigurationOptions. The attribute "Servers" has no outcome to the app. 

**Screenshots**
![image](https://github.com/Azure/azure-functions-openapi-extension/assets/105053851/7d04a0f1-cca4-40db-a708-c99006c5b206)
![image](https://github.com/Azure/azure-functions-openapi-extension/assets/105053851/3855c929-46e4-47ba-a5df-4a8f0cb1962a)

**Comment by slaneyrw** [comment]
This is resolved by https://github.com/Azure/azure-functions-dotnet-worker/pull/2149 and is in the latest Worker nuget packages

**Comment by Glowiksi** [comment]
@slaneyrw Thanks for the reply and the work you have provided. It did fix my issue. 

For future search: when running into this issue also make sure to remove the "Server = ..GetHostNames()" this will lead to other routing issues.
