### ISSUE TITLE
Generics not recognized well with OpenApiResponseWithBodyAttribute

### ISSUE THREAD

**Issue by powerdude** [Azure/azure-functions-openapi-extension#64]
When using `OpenApiResponseWithBody` on 2 different methods with a generic `MyResponse<int>` and then `MyResponse<string>`, the UI doesn't render.  Also, if only used on one method, the properties of `MyResponse` do not show in the Models section.

**Comment by justinyoo** [comment]
@powerdude Thanks for the issue. To repro on my side, could you provide more details how you got into that, including your class definitions?

**Comment by powerdude** [comment]
```

 public class Response<T>
    {
        public Response()
        {
            ErrorCodes = new List<Error>();
            DebugMessage = "";

            Result = new Result<T>();
        }

        [JsonProperty("result")] public Result<T> Result { get; set; }

        [JsonProperty("debugMessage")] public string DebugMessage { get; set; }

        [JsonProperty("errorCodes")] public List<Error> ErrorCodes { get; set; }
    }

  public class Result<T>
    {
        [JsonProperty("value")] public T Value { get; set; }
    }

public class Error
    {
        [JsonProperty("message")] public string Message;
        [JsonProperty("error")] public string Type { get; set; }
    }

public class Router{}

  public class Bug
    {
        [FunctionName(FunctionNames.AddRouter)]
        [OpenApiOperation(operationId: nameof(AddRouter), tags: new[] { "router" }, Summary = "Adds a router", Description = "Registers a new router in the system", Visibility = OpenApiVisibilityType.Important)]
        [OpenApiRequestBody("application/json", typeof(Router), Required = true)]
        //[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(Response<RouterCreationSuccess>), Summary = "The response", Description = "This returns the response")]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.MethodNotAllowed, Summary = "Invalid input", Description = "Invalid input")]
        public async Task<IActionResult> AddRouter(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "router")]
            HttpRequest req,
            [FromBody] Router newRouter,
            ILogger log)
        {
            return null;
        }
        [FunctionName("FunctionNames.AddRouter2")]
        [OpenApiOperation(operationId: nameof(AddRouter), tags: new[] { "router" }, Summary = "Adds a router", Description = "Registers a new router in the system", Visibility = OpenApiVisibilityType.Important)]
        [OpenApiRequestBody("application/json", typeof(Router), Required = true)]
        //[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(Response<int>), Summary = "The response", Description = "This returns the response")]
        [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.MethodNotAllowed, Summary = "Invalid input", Description = "Invalid input")]
        public async Task<IActionResult> AddRouter2(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "router")]
            HttpRequest req,
            [FromBody] Router newRouter,
            ILogger log)
        {
            return null;
        }
    }

```

**Comment by powerdude** [comment]
this is the error i get if both use `Response<T>`:  

```
[2021-03-10T01:15:20.522Z] Executed 'RenderSwaggerDocument' (Failed, Id=a442e2f7-a52c-4ccd-90d5-ea434e996a74, Duration=91ms)
[2021-03-10T01:15:20.524Z] System.Private.CoreLib: Exception while executing function: RenderSwaggerDocument. System.Private.CoreLib: An item with the same key has already been added. Key: response.
```

and if i change `Response<int>` to just `int`, then no error but the `Response<RouterCreationSuccess>` doesn't show correctly in models section

**Comment by Arseth** [comment]
Same problem here when using ```OpenApiResponseWithBody``` with a generic type ```MyGenericClass<Data>```

**Comment by ssa3512** [comment]
@justinyoo  I can pick this up if you give me some guidance on what the correct result should be. The call that is failing is Line 253 here because `GetOpenApiTypeName` is returning the generic root. If two methods have two responses with the same generic root and different type params the dictionary tries to add twice with the same key. https://github.com/Azure/azure-functions-openapi-extension/blob/2a58b606a59b8fd90ce0b02ae2c402a47f970ecf/src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/DocumentHelper.cs#L251-L255

Based on what I am seeing in the samples, the convention being used for generics is to append a `_` to the generic type with the generic type param.

![image](https://user-images.githubusercontent.com/1991399/113461106-40472700-93e9-11eb-9252-8b7c4805fcb0.png)

**Comment by justinyoo** [comment]
@powerdude It's been released to [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.6.0-preview). Please have a look and let us know.

**Comment by powerdude** [comment]
thanks @justinyoo .  I've already changed my object structure since i was under a timeline crunch, but if it works for the sample, then i'll eventually migrate back to my old setup.  Thanks for the fix!

**Comment by Vivannaboa** [comment]
Hello, with a generic type it's working now.
Here I am having a problem when there are two generic types.

it works:

`Response<T>`

It does not work:

`Response<IEnumerable<T>>`

![image](https://user-images.githubusercontent.com/11863525/139668852-82b94db5-d334-4067-ad37-4034afb080fe.png)
![image](https://user-images.githubusercontent.com/11863525/139670286-7dba27d1-a247-45cc-9bcb-302cc2402ce9.png)
