### ISSUE TITLE
Exception thrown trying to render any endpoint from the OpenAPI endpoints

### ISSUE THREAD

**Issue by slaneyrw** [Azure/azure-functions-openapi-extension#658]
**Describe the issue**
Any call to an endpoint exposed from Microsoft.Azure.Functions.Worker.Extensions.OpenApi ( i.e. swagger/ui ) is thrown an exception

Executed 'Functions.RenderSwaggerDocument' (Failed, Id=81324a28-8c5e-41ed-9b31-94192d057005, Duration=735ms)
System.Private.CoreLib: Exception while executing function: Functions.RenderSwaggerDocument. System.Private.CoreLib: Result: Failure
Exception: System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.get_StatusCode()

This appears related to
https://github.com/Azure/azure-functions-dotnet-worker/discussions/2396

as we are using the Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore package.

Endpoints in the function app all return action results and execute successfully.

According to the source generator GeneratedFunctionExecutor.g.cs, RenderOpenApiDocument is returning an HttpResponseData.

**Expected behavior**
All swagger endpoints render

**Comment by slaneyrw** [comment]
Here is the offending commit
https://github.com/Azure/azure-functions-dotnet-worker/pull/2322

**Comment by slaneyrw** [comment]
Reverting to Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore 1.2.1 restored the functionality

**Comment by slaneyrw** [comment]
This may be resolved by

https://github.com/Azure/azure-functions-dotnet-worker/pull/2488

**Comment by satvu** [comment]
Yes, this should be fixed in 1.3.1 - please follow https://github.com/Azure/azure-functions-dotnet-worker/issues/2479 instead for when the package releases.

> This may be resolved by
> 
> [Azure/azure-functions-dotnet-worker#2488](https://github.com/Azure/azure-functions-dotnet-worker/pull/2488)
