### ISSUE TITLE
Guidance On Plugging Into OpenApiSecurity For JWT Bearer Tokens

### ISSUE THREAD

**Issue by rhizohm** [Azure/azure-functions-openapi-extension#67]
Can you point me to documentation/code samples of how to plug into the `OpenApiSecurity `attribute? Our scenario is where we have our own attribute that inherits from the `AuthorizeAttribute ` that we decorate our functions with. How do we wire up the OpenApiSecurity attribute so that the "Try It Now" feature will work?

**Comment by justinyoo** [comment]
@rhizohm Hope this sample code helps:

https://github.com/Azure/azure-functions-openapi-extension/blob/e81e82032c936b9fe68c4413da313c6c9590ea82/samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static/DefaultHttpTrigger.cs#L17-L27

**Comment by justinyoo** [comment]
Also this is the doc for it: https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#openapisecurityattribute
