### ISSUE TITLE
Annotation with bodyType does not show JsonPropertyName of model class

### ISSUE THREAD

**Issue by crutchfield** [Azure/azure-functions-openapi-extension#72]
I have a POCO annotated with JsonPropertyName for each member.  When passing the class type to the OpenApiResponseWithBody annotation as the bodyType I do not get the JsonPropertyNames I get the class member names instead in the generated swagger and open api documents.

**Comment by justinyoo** [comment]
@crutchfield Thanks for the issue! Could you share how to repro the issue on my end?

**Comment by crutchfield** [comment]
> @crutchfield Thanks for the issue! Could you share how to repro the issue on my end?

I have a simple POCO.  Like such: 

    public class PocoRequest
    {   
        [JsonPropertyName("request_id")]
        public long Id { get; set; }

        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        [JsonPropertyName("mgrs_location")]
        public string Location { get; set; }
   }

When documenting my API such as follows: 

    public static class MyAPIs
    {

        [OpenApiOperation(
            operationId: "getById",
            tags: new[] { "MyAPI" },
            Summary = "Get request",
            Description = "Retrieve a request by id from store.",
            Visibility = OpenApiVisibilityType.Important)]
        [OpenApiParameter(
            name: "id",
            In = ParameterLocation.Path,
            Required = true,
            Type = typeof(int),
            Summary = "Request ID",
            Description = "The Id of Request to retrieve",
            Visibility = OpenApiVisibilityType.Important)]
        [OpenApiResponseWithBody(
            statusCode: HttpStatusCode.OK, 
            contentType: "application/json", 
            bodyType: typeof(PocoRequest), 
            Description = "The OK response")]
        [OpenApiResponseWithoutBody(
            statusCode: HttpStatusCode.NotFound, 
            Summary = "Invalid input", 
            Description = "Invalid input")]
        [FunctionName(nameof(GetById))]
        public static async Task<IActionResult> GetById(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "myapi/{id}")] HttpRequest req,
            int id,
            ILogger log)
        {
        }
}

In the swagger or open api documents I'd expect to see response body model described with request_id and not Id.  The same for mgrs_location - not location.  Seems to pick up on method name and not JsonPropertyName set name.

**Comment by justinyoo** [comment]
Oh, I now see what you mean. Can you please try `JsonProperty("something")` instead of `JsonPropertyName("something")`?

If the `JsonPropertyName` decorator comes from `System.Text.Json`, unfortunately, it's not supported yet.

**Comment by crutchfield** [comment]
Thanks for your help. I will try you suggestion.  Yes, the decorator is from System.Text.Json.  But since unsupported I suppose closing issue is appropriate.

**Comment by crutchfield** [comment]
P.S.  Suggestion worked perfectly.
