### ISSUE TITLE
Arrays of arrays doesn't work

### ISSUE THREAD

**Issue by Assassinbeast** [Azure/azure-functions-openapi-extension#75]
Hi, models that have `List<List<string>>` or `Dictionary<string, List<string>>` properties get generated incorrectly

For example, if i have a function like this

```
public class Foo
{
	public List<List<string>> Items { get; set; }
}

public class TestFunction
{
	[FunctionName("Test")]
	[OpenApiOperation(operationId: "Test")]
	[OpenApiResponseWithBody(HttpStatusCode.OK, "application/json", typeof(Foo))]
	public IActionResult GetTest(
		[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "test")] HttpRequest req)
	{
		return new OkResult();
	}
}
```

Then the Items property will become an string array, and not an array of arrays.

![image](https://user-images.githubusercontent.com/6762656/111887978-ec941100-89d8-11eb-9ecb-b3b8d359d412.png)

The same happens if i have a `Dictionary<string, List<string>>` .
Then the property will become `Dictionary<string, string>`

**Comment by justinyoo** [comment]
@Assassinbeast Thanks for the issue! I can repro the issue on my end. Let me check.

**Comment by justinyoo** [comment]
@Assassinbeast It's been released to [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.6.0-preview). Please have a look and let us know.

**Comment by Assassinbeast** [comment]
> @Assassinbeast It's been released to [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.OpenApi/0.6.0-preview). Please have a look and let us know.

Amazing! Seems to be working. 
Thanks :-)
