### ISSUE TITLE
Range annotation not respected

### ISSUE THREAD

**Issue by crutchfield** [Azure/azure-functions-openapi-extension#76]
Is there a way to annotate models so the Open API spec show constraints like minimum and maximum in description section?  

Using
       [Range(-90.0, 90.0)]
       public double latitude { get; set; }

Does not reflected latitude in the spec description with a "minimum": -90 or "maximum": 90.

**Comment by justinyoo** [comment]
@crutchfield Thanks for the issue! It's not supported yet. But it could be possible to add this feature.
