### ISSUE TITLE
Swagger.json using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by marceloodiniz** [Azure/azure-functions-openapi-extension#77]
I am using "**Microsoft.Azure.WebJobs.Extensions.OpenApi**" version "**0.5.1-preview**" and having problems when I publish my Function App. _Swagger UI_ is using HTTPS but _swagger.json_ is using HTTP. My Function App is configured to use "HTTPS Only" and "Minimum TLS Version" as "1.2".

**Swagger UI**

![image](https://user-images.githubusercontent.com/6569081/112054236-144bbc00-8b34-11eb-9515-540d236b7114.png)

**Swagger.json**

![image](https://user-images.githubusercontent.com/6569081/112054396-465d1e00-8b34-11eb-884f-e4b4a194eaaa.png)

I tried to override the list of openapi servers creating a class that inherit from "DefaultOpenApiConfigurationOptions". But I needed the HttpRequest object, and this class does not permit inject values, it is created using Activator.CreateInstance. 

What should I do?

**Comment by justinyoo** [comment]
@marceloodiniz Unfortunately, I'm not able to reproduce your issue on my end.

Here's the screenshot I presented at Global Integration Bootcamp about less than a month ago, which uses the same **v0.5.1-preview**.

![image](https://user-images.githubusercontent.com/1538528/112064465-56154a80-8ba6-11eb-97d7-fa0b7578284d.png)

Can you please try the sample code in this repo and check if it's working or not on your end?

**Comment by marceloodiniz** [comment]
Hi @justinyoo.

I get the sample project and have the same problem:

![image](https://user-images.githubusercontent.com/6569081/112385155-09c52a00-8cce-11eb-8d77-183a893d5076.png)

If I change the swagger.json url on Swagger UI to use HTTPS, it works:

![image](https://user-images.githubusercontent.com/6569081/112385702-ae476c00-8cce-11eb-96bd-4bff602a2453.png)

Maybe is some config on Function App.

**Comment by jscheeres** [comment]
Same issue here

**Comment by justinyoo** [comment]
@marceloodiniz Thanks for the issue! A new version, v0.6.0-preview, has been released and if I use the new version, it sorts out your issue from my end. Could you please have a look and let us know?

**Comment by justinyoo** [comment]
@marceloodiniz As I haven't heard from you for a while, I'm closing this issue for now. If you still have the same issue, please open a new one and link to this.

**Comment by marceloodiniz** [comment]
@justinyoo, the new version (v0.6.0-preview) did **NOT** resolved my problem!

**Comment by mikemassa84** [comment]
@justinyoo, I am having the same issue and narrowed the cause down to running a function app on a Linux hosted app service plan.

Here is what I found:

- Windows Consumption Plan - Success
- Linux Consumption Plan - Success
- Linux Hosted Plan (P1v2) - **Failure**

You can see the error here:
https://openapitestl.azurewebsites.net/api/swagger/ui

I used the same function code on each plan. It is the Function1 template that is created by Visual Studio (2019) when picking the Http trigger with OpenAPI option.

```
public static class Function1
{
	[FunctionName("Function1")]
	[OpenApiOperation(operationId: "Run", tags: new[] { "name" })]
	[OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
	[OpenApiParameter(name: "name", In = ParameterLocation.Query, Required = true, Type = typeof(string), Description = "The **Name** parameter")]
	[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Description = "The OK response")]
	public static async Task<IActionResult> Run(
		[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
		ILogger log)
	{
		log.LogInformation("C# HTTP trigger function processed a request.");

		string name = req.Query["name"];

		string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
		dynamic data = JsonConvert.DeserializeObject(requestBody);
		name = name ?? data?.name;

		string responseMessage = string.IsNullOrEmpty(name)
			? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
			: $"Hello, {name}. This HTTP triggered function executed successfully.";

		return new OkObjectResult(responseMessage);
	}
}
```

**Comment by justinyoo** [comment]
@mikemassa84 Thanks for the issue! It seems that we would need to raise the issue to the other place because it looks more relevant to the instance itself, rather than this library. Would you please raise the issue to [here](https://github.com/Azure/Azure-Functions/issues) and tag this issue?
