### ISSUE TITLE
Do all functions in the project have to be configured?

### ISSUE THREAD

**Issue by buddyackerman** [Azure/azure-functions-openapi-extension#78]
I have a single function app/project.  Some of the functions are queue trigger functions others I don't have and don't want Open API configuration for.  I'm not sure if that's what's causing the error below but I tried setting up Open API on a test project/function app that I have (which has only one function that I setup OpneAPI for) and it worked fine so I am wondering if my problem is having queue triggers and undefined http trigger functions in the same function app.

The below error  is what I get when running the function app locally I try to access the swagger UI.

[2021-03-29T20:39:51.921Z] Executing 'RenderSwaggerUI' (Reason='This function was programmatically called via the host APIs.')

[2021-03-29T20:39:51.931Z] SwaggerUI page was requested.

[2021-03-29T20:39:52.077Z] Executed 'RenderSwaggerUI' [2021-03-29T20:39:52.079Z] System.Private.CoreLib: Exception while executing function: RenderSwaggerUI. System.Linq: Value cannot be null. (Parameter 'source').

**Comment by justinyoo** [comment]
@buddyackerman Thanks for the issue!

With regards to exposing to OpenAPI document, only functions with the `[HttpTrigger]` binding are considered. And those selected endpoints are filtered by the `[OpenApiOperation]` decorator.

Therefore, any function other than HTTP trigger won't be selected. Any HTTP trigger function without the `[OpenApiOperation]` decorator won't be selected either.

If you still face the issue, it would be great to let us know how to reproduce the error on our end.

**Comment by justinyoo** [comment]
@buddyackerman As I haven't heard from you for a while, I'm closing this issue for now. If you still have the same issue, please open a new one and link to this.
