### ISSUE TITLE
Active Directory B2C Auth Configuration

### ISSUE THREAD

**Issue by Raysapps** [Azure/azure-functions-openapi-extension#85]
I've configured Azure Active directory B2C  auth flow by adding a new class  'B2CAuth' derived from the 'OpenApiOAuthSecurityFlows' interface. Unfortunately, the API Authorization is unsuccessful and returned 401 - UnAuthorized error in the swagger UI.
The code is given below. Not sure if I am missing any config settings.  Could anyone please advise?
` 
 class B2CConfigAuth : OpenApiOAuthSecurityFlows
    {
        public B2CConfigAuth()
        {
            Implicit = new OpenApiOAuthFlow()
            {
                // Add b2C auth url.
                AuthorizationUrl = new Uri(""),
                // Add b2c API scope
                Scopes = new Dictionary<string, string> { { "openid", "OpenID" }, { "<b2cscope>","AppIDURI" } }
            };
        }
    }

    // HTTP Get Method
    public static class B2CAuthTest
    {
        [OpenApiOperation(operationId: "OpenAPITest", tags: new[] { "name" })]
        [OpenApiSecurity("b2cAuth", SecuritySchemeType.OAuth2, In = OpenApiSecurityLocationType.Header, Scheme = OpenApiSecuritySchemeType.Bearer, Flows = typeof(B2CConfigAuth))]
        [OpenApiParameter(name: "name", In = ParameterLocation.Query, Required = true, Type = typeof(string), Description = "The **Name** parameter")]
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(string), Description = "The OK response")]
        [FunctionName("OpenAPITest")]
        public static async Task<IActionResult> OpenAPITest(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            string name = req.Query["name"];
            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";
            return new OkObjectResult(responseMessage);
        }
    }`

**Comment by justinyoo** [comment]
@Raysapps Thanks for the issue! I don't think your code works as expected. Would you please follow this document and let us know? https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#openapisecurityattribute

**Comment by Raysapps** [comment]
I noticed that the swagger shows invalid errors provided below when the "Log in with Azure Active Directory" option is set in the Azure Portal.
// error list
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://xxxxxx.azurewebsites.net/api/swagger.json"}]}

However, the swagger doc becomes valid by resetting the option to "Allow Anonymous request (no action)". Is this the expected behavior? 

I still get 401- UnAuthorized error when the option "Allow Anonymous request(no action)" is selected in the Azure portal.  Is it possible to have both anonymous functions and Active directory B2C Authorized APIs within the same Azure function App? If yes, could you please advise?
