### ISSUE TITLE
Invalid Route Path Error

### ISSUE THREAD

**Issue by Raysapps** [Azure/azure-functions-openapi-extension#86]
Initializing the Route parameter in the HTTPAttribute is resulting in undefined path errors in the generated swagger file. Could you please advise? 

// Swagger Errors
{"messages":[""attribute paths.'/AddUserAccount'(post).responses is missing","attribute paths.'/Account/DeleteUserAccount'(delete).responses is missing","attribute]
 }
`public async Task<IActionResult> AddUserAccount(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "AddUserAccount")] HttpRequest req,
            ILogger log)
        {
           // await azureAccount.AddUserAccount(req.Claims());
            return new OkResult();
         }
`
`

**Comment by justinyoo** [comment]
@Raysapps Have you added `[OpenApiResponseWithBody()]` or `[OpenApiResponseWithoutBody()]` decorators?

This document helps you: https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/enable-open-api-endpoints.md#enable-openapi-document

**Comment by Raysapps** [comment]
Thank you for sharing the relevant doc.  I've migrated a lot of Asp.net core web APIs to Azure HTTP functions and noticed invalid errors in the swagger UI after publishing to Azure. Is it possible to report them as errors at build time?

**Comment by danielabbatt** [comment]
Yes it would be nice to have an optional analyser package to suggest
missing attributes etc.

**Comment by justinyoo** [comment]
@Raysapps @danielabbatt That's a good idea! Let me dig into it.
