### ISSUE TITLE
Byte[] support

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#96]
Related to: https://github.com/aliencube/AzureFunctions.Extensions/issues/119

**Comment by punthoofd07** [comment]
Following, would like this feature as well since I have the same issue.
Thanks

**Comment by Cznielsen** [comment]
I am following this as well.

**Comment by nikolic-m** [comment]
> I am following this as well. Is there some temporary fix to this besides writing the system to use an encoded string on the exposed models?

You can add "custom" byte visitor from https://github.com/aliencube/AzureFunctions.Extensions/issues/119#issuecomment-732220807 this way:
```
private string GetSwaggerDocument()
{
    var visitorCollection = GetVisitorCollection();
  
    result = await document
        .InitialiseDocument()
        .AddMetadata(OpenApiInfo)
        .AddServer(req, "api")
        .AddVisitors(visitorCollection)
        .Build(Assembly)
        .RenderAsync(OpenApiSpecVersion.OpenApi3_0, OpenApiFormat.Json);
  
    return result;
}

private VisitorCollection GetVisitorCollection()
{
    var collection = VisitorCollection.CreateInstance();
    var byteVisitor = new ByteTypeVisitor(collection);

    collection.Visitors.Add(byteVisitor);

    return collection;
}
```

**Comment by choipureum** [comment]
Hi @justinyoo , can I take this issue as my assignment?👀

**Comment by tommck** [comment]
@justinyoo @choipureum should this have also fixed `Nullable<byte>`?  I'm having the same error and the only thing I can find in my object tree is a `Nullable<byte>`

**Comment by Poppyto** [comment]
> Does it work for multiple file uploads? Like List<byte[]>? Because I got an error when I try that: `Could not resolve reference: Could not resolve pointer: /components/schemas/list_byte does not exist in document`

it seems List_[Type] is not generated in swagger.json, so I add it as a workaround

```
public class OpenApiDocumentFilter : IDocumentFilter
{
    public void Apply(IHttpRequestDataObject req, OpenApiDocument document)
    {           
        document.Components.Schemas.TryAdd("list_byte", new OpenApiSchema()
        {
            Type = "string",
            Format = "binary"
        });
    }
}
```
