### ISSUE TITLE
Upload File feature request

### ISSUE THREAD

**Issue by Assassinbeast** [Azure/azure-functions-openapi-extension#97]
I have a feature request to upload a binary file.

When i use Insomnia, i can choose the Body to be a "Binary File" which is what i wish to do through Swagger.
![image](https://user-images.githubusercontent.com/6762656/115252269-9fb46f00-a12b-11eb-8327-ac84e6668ff6.png)

If it will get implemented, it could for example look like this: `[OpenApiRequestBody("application/pdf", typeof(byte[]))]`

I believe its in this Swagger docs: https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by justinyoo** [comment]
Related to #96
