### ISSUE TITLE
System.ArgumentException: 'An item with the same key has already been added. Key: iApiResponse'

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-functions-openapi-extension#99]
Ran into a similar issue in the following scope:

There are two Azure HTTP-triggered functions with the following attributes:

```cs
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(IApiResponse<User>), Description = "The OK response containing the user's data in the response body.", HeaderType = typeof(string)]
```
And
```cs
[OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "text/plain", bodyType: typeof(IApiResponse<bool>), Description = "The OK response")]
```

Invoking swagger's UI causes the exception in the title of this issue. The full stack trace is per below:

   

> at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
>    at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.DocumentHelper.GetOpenApiSchemas(List`1 elements, NamingStrategy namingStrategy, VisitorCollection collection)
>    at Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Document.Build(Assembly assembly)
>    at Microsoft.Azure.WebJobs.Extensions.OpenApi.OpenApiHttpTrigger.<RenderSwaggerDocument>d__5.MoveNext() in C:\Users\arash.sabet\.nuget\packages\microsoft.azure.webjobs.extensions.openapi\0.5.1-preview\contentFiles\any\netstandard2.0\OpenApi\OpenApiHttpTrigger.cs:line 49

**Comment by arashcomsense** [comment]
@@justinyoo any updates on this issue?

**Comment by justinyoo** [comment]
Related to : #94

**Comment by RealGoodAnthony** [comment]
This may be related #356

**Comment by justinyoo** [comment]
#610 takes care of this issue. The fix will be released in the next `v2-preview` release.
